### ISSUE TITLE
Spawn Bug? [Issue marked as invalid]

### ISSUE THREAD

**Issue by SomeRandomBro** [0SoggyMustache0/ZAWA#1]
**Describe the bug**
Well... Idk if this is a bug or something but, I was really excited for the 2.0.0 version and it is incredible congrats for the great work but, I think that the spawns are, I wouldn't say broken but they are pretty low like, I tried to increase the spawn chance in the configs but, the animals appear in a pretty low rate, there were some animals that I've put the spawn chance to 80 and the almost don't appear, if they don't appear indeed, I have just the zawa, bookworm, better fps and optifine installed.

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1.
2.
3.
4.
More steps...

**Expected behavior**
The animals to spawn normally around the world.

**Screenshots**

** Crash Report or Game Log**
None

**Please complete the following information):**
 - Mod Version Number : 2.0.0
 - Bookworm Version Number : 2.5.0
 - Forge Version Number : 1.12.2-forge1.12.2-14.23.5.2847
 - Is OptiFine installed? : Yes

**Additional context**
Everything is working well, except for the spawns, idk if it is just me. Except for this, the mod is amazing, just amazing the best mod for animals in my opinion, keep up the good work :)

**Comment by JoelZBub** [comment]
Use your configs.
Spawn rates are not an issue and this will no longer be discussed
