### ISSUE TITLE
Data book not showing diets.

### ISSUE THREAD

**Issue by coffeeraccoon69** [0SoggyMustache0/ZAWA#10]
**Describe the bug**
Data book shows everything but diets for tamed and wild animals. I removed all other mods that might conflict with ZAWA and bookworm but it doesn't change anything. The data book shows diets for wild and tamed animals in single player (With and without the other mods) but on my multiplayer server the diet section is blank but everything else in the data book shows up. 

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. Launched the multiplayer server.
2. Connected to it.
3. Once in, went over to one of my tamed pangolins and used the data book.
4. Flipped through the pages to see the new updates but noticed the diet page was blank.
More steps...

**Expected behavior**
Expected diet page to not be blank.

**Screenshots**
![Pangolin](https://user-images.githubusercontent.com/62524322/77263449-61325380-6c90-11ea-82c8-73f9874d8ed9.png)

** Crash Report or Game Log**
Already sent several game logs to Soggy but they said the logs had no useful information.

**Please complete the following information):**
 - Mod Version Number :1.12.2-2.0.0
 - Bookworm Version Number :1.12.2-2.5.0
 - Forge Version Number :1.12.2-14.23.5.2768
 - Is OptiFine installed? : no
 - Is this bug present in single player or on a server or both? : Server
 
**Additional context**
Nothing else i can add.

**Comment by JoelZBub** [comment]
Able to replicate this issue while playing on server.
This image is Single Player:
![2020-03-22_20 52 32](https://user-images.githubusercontent.com/12024500/77269903-b1091e80-6c80-11ea-9dfa-9dc482ab85c1.png)
This image is Multiplayer :
![2020-03-22_20 52 12](https://user-images.githubusercontent.com/12024500/77269928-c716df00-6c80-11ea-9100-a177fa51059b.png)

**Comment by 0SoggyMustache0** [comment]
Issue replicated and fixed for 2.0.1
