### ISSUE TITLE
[Feature Request] Spawn Eggs should be compatible with dispensers

### ISSUE THREAD

**Issue by VakyPanda** [0SoggyMustache0/ZAWA#100]
**Feature requests that do not follow this template will be ignored and closed**
**Do NOT suggest animals or model change**

**Is your feature request related to a problem? Please describe.**
Zawa animal spawn eggs are not compatible with dispensers, and just drop the item instead of an entity when activated in a dispenser

**Describe the solution you'd like**
Please make spawn eggs spawn the corresponding entity when activated within a dispenser

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by 0SoggyMustache0** [comment]
I'll look into making this a thing when I can. Good suggestion.

**Comment by 0SoggyMustache0** [comment]
This feature has been coded and will be available in 2.1. Thank you for the good suggestion.
