### ISSUE TITLE
[Feature Request] Extend shift right click variant spawning for all animals

### ISSUE THREAD

**Issue by Lysaell** [0SoggyMustache0/ZAWA#102]
**Is your feature request related to a problem?**
Nah, not related with a problem. This would just add some extra functionality.  

**Solution**
I mean, it speaks for itself. Add the same shift right click functionality that gives you the option to spawn subspecies to all animals with variants so the player can keep spawning a specific variant. This can just stick with the variant 1, variant 2, etc system and the player can figure out what color that is. 

**Alternatives**
Yup! The spawn command is a very easy alternative to this. But there is a large audience that doesn't want to mess with those and I do admit it can be a tad annoying to deal with them when there could be a potential shift right click to get what I want. 

**Additional context**
nah.

**Comment by 0SoggyMustache0** [comment]
Thank you for the good suggestion. I have added this feature and it will be available in 2.1.
