### ISSUE TITLE
[Bug] Orca texture is bugged.

### ISSUE THREAD

**Issue by TheAnnoyingOrca** [0SoggyMustache0/ZAWA#110]
**Describe the bug**
When spawned, orcas exhibit broken texture, flashing from working and purple textures.

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. Open Minecraft with ZAWA and open a creative world.
2. Spawn the Orca entity.
3. Boom, done.

**Expected behavior**
I expected the orca texture to appear as it did in the 2.0 update, and it did for the most part, aside from the broken texture.

**Screenshots**
(https://cdn.discordapp.com/attachments/669092323103080492/726175581682663484/2020-06-26_13.38.53.png)

** Crash Report or Game Log**
The game didn't crash.

**Please complete the following information):**
 - Mod Version Number : 2.1.0
 - Bookworm Version Number : 2.5.2
 - Forge Version Number : 2854
 - Are other mods installed? : None
 - Is OptiFine installed? : No
 - Is this bug present in single player or on a server or both? : Unknown, currently only known in singleplayer.
 
**Additional context**
None

**Comment by 0SoggyMustache0** [comment]
Oop that's no good. I'll fix that for the next patch. Thank you for the report.

**Comment by TheAnnoyingOrca** [comment]
The same thing occurs with the Amsterdam Albatross. :(

**Comment by xjordannx** [comment]
Also the meerkat when running

**Comment by JoelZBub** [comment]
I guess we would have caught this **IF THE ORCAS SPAWNED NATURALLY**

**Comment by 0SoggyMustache0** [comment]
https://www.curseforge.com/minecraft/mc-mods/bookworm/files/2989715
