### ISSUE TITLE
[Bug] Adult Albatross doesnt spawn in egg when right clicked with spawn egg

### ISSUE THREAD

**Issue by VakyPanda** [0SoggyMustache0/ZAWA#113]
**Issues that dont follow this template will be ignored and closed**

**Describe the bug**
The albatross spawns in a baby instead of an egg when right clicked with a spawn egg

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1.Spawn Albatross
2.Right Click with spawn egg
3.Baby Spawns

**Expected behavior**
The egg should spawn instead of the baby

**Screenshots**
N/A

**Crash Report or Game Log**
N/A

**Please complete the following information:**
 - Mod Version Number : zawa-1.12.2-2.1.0
 - Bookworm Version Number : bookworm-1.12.2-2.5.2.1
 - Forge Version Number : forge-14.23.5.2854
 - Are other mods installed? : No
 - Is OptiFine installed? : No
 - Is this bug present in single player or on a server or both? : Only tested in single player
 
**Additional context**
N/A

**Comment by 0SoggyMustache0** [comment]
Unable to duplicate
