### ISSUE TITLE
[Bug]  Enrichment items, plushes, lamp bases etc should not connect to walls and fences

### ISSUE THREAD

**Issue by VakyPanda** [0SoggyMustache0/ZAWA#116]
**Issues that dont follow this template will be ignored and closed**

**Describe the bug**
Enrichment / Plushes / Zawa decor connects to walls and fences 

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1.Place Fence
2.Place plush next to it
3.They connect

**Expected behavior**
They shouldn't connect with each other

**Screenshots**
![2020-06-27_04 49 46](https://user-images.githubusercontent.com/63160430/85908182-b2bf2100-b831-11ea-8a3d-01d355b8cc53.png)

** Crash Report or Game Log**
N/A

**Please complete the following information):**
 - Mod Version Number : zawa-1.12.2-2.1.0
 - Bookworm Version Number : bookworm-1.12.2-2.5.2.1
 - Forge Version Number : forge-14.23.5.2854
 - Are other mods installed? : No
 - Is OptiFine installed? : No
 - Is this bug present in single player or on a server or both? : Only Tested In Single Player
 
**Additional context**
N/A

**Comment by 0SoggyMustache0** [comment]
Thank you for the report. This will be fied in the 2.1 patch.
