### ISSUE TITLE
[Bug] Some animals are textured, some aren't.

### ISSUE THREAD

**Issue by Wolfoxxite** [0SoggyMustache0/ZAWA#118]
Some animals are textured and some aren't.. ALL baby animals have a whole untextured "tposed" type model of top of them

I was just checking out all the animals, to see what they look like, and they all don't really have textures!

BABY RED PANDA:
https://imgur.com/SL2xrN1

ADULT ORCA:
https://imgur.com/O1sWFSw
(this applies to all animals)

 - Mod Version Number : 2.1.0
 - Bookworm Version Number : 2.5.2
 - Forge Version Number : 2854
 - Are other mods installed? : 
 - Is OptiFine installed? : yes
 - Is this bug present in single player or on a server or both? : both

**Comment by 0SoggyMustache0** [comment]
Update bookworm
