### ISSUE TITLE
[Bug] Grizzly Bears sleep with they're eyes wide open

### ISSUE THREAD

**Issue by Karakhighway123** [0SoggyMustache0/ZAWA#12]
**Issues that dont follow this template will be ignored and closed**

**Test before making a report by removing all mods except ZAWA, Bookworm and ZAWA Add-ons. Check that you are using the latest versions of these mods. Delete these lines when making a report.**

**Describe the bug**
 The Grizzlt Bear does not close its eyes while sleeping

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. Was Building
2. Breeding Grizzly Bears
3. 
4.
More steps...

**Expected behavior**
Expected them too sleep with their eyes closed 

**Screenshots**

** Crash Report or Game Log**
If your game crashed, paste your crash report to https://pastebin.com/ or similar service and paste the link in place of this sentence.

**Please complete the following information):**
 - Mod Version Number : zawa 2.0.0
 - Bookworm Version Number : bookworm 2.5.0
 - Forge Version Number : 14.23.5.2847
 - Is OptiFine installed? : yes
 - Is this bug present in single player or on a server or both? : single player
 
**Additional context**
Adult Grizzly Bears do not sleep with they're eyes closed and it looks creepy.

**Comment by 0SoggyMustache0** [comment]
Fixed for 2.0.1
