### ISSUE TITLE
[Feature Request] I would like to see a thing implemented in this mod

### ISSUE THREAD

**Issue by homelyseven250** [0SoggyMustache0/ZAWA#121]
**Feature requests that do not follow this template will be ignored and closed**
**Do NOT suggest animals or model change**

**Is your feature request related to a problem? Please describe.**
My problem is that the mod (I think), isn't compatible with biome bundle, even if you use the biome bundle o plenty.

**Describe the solution you'd like**
I would like integration with Biome Bundle / Biome bundle o plenty, like Biomes O' Plenty.

**Describe alternatives you've considered**
I could use biomes o plenty, but it has a lot less biomes.

**Additional context**
I don't think there is any.

**Comment by 0SoggyMustache0** [comment]
This mod supports BOP read the FAQ on this repo.
