### ISSUE TITLE
[Bug] Crash with Kemonocraft upon world load

### ISSUE THREAD

**Issue by LegendaryCrystalFox** [0SoggyMustache0/ZAWA#123]
**Issues that dont follow this template will be ignored and closed**

**Test before making a report by removing all mods except ZAWA, Bookworm and ZAWA Add-ons. Check that you are using the latest versions of these mods. Delete these lines when making a report.**

**Describe the bug**
When installed with Kemonocraft game crashes upon loading a world

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. Loading a World
2.
3.
4.
More steps...

**Expected behavior**
To have both mods run fine together
**Screenshots**

** Crash Report or Game Log**
https://pastebin.com/EFwdCQq9

**Please complete the following information):**
 - Mod Version Number : 2.1.0
 - Bookworm Version Number : 2.5.2.1
 - Forge Version Number : 14.23.5.2854
 - Are other mods installed? : Yes
 - Is OptiFine installed? : No
 - Is this bug present in single player or on a server or both? : Single Player
 
**Additional context**
Kemonocraft worked fine with Zawa verison: 2.0.35

**Comment by 0SoggyMustache0** [comment]
You have core mods installed. Contact their authors first, I cannot find anything that would be an issue in my code unless you have a broken biome config.

**Comment by LegendaryCrystalFox** [comment]
![Screenshot_2020-06-30-02-07-25](https://user-images.githubusercontent.com/34899528/86089589-7e887200-ba76-11ea-8ffd-2570765e60fc.jpeg)

**Comment by 0SoggyMustache0** [comment]
Is this the right mod? https://www.curseforge.com/minecraft/mc-mods/kemonocraft/files I just downloaded it and was able to run the mods together just fine. The code the crash is pointing to hasn't been changed in many versions unless I'm mistaken.

**Comment by JoelZBub** [comment]
As a side point... there is absolutely ZERO reason to allocate 16GB to your MC instance.

**Comment by LegendaryCrystalFox** [comment]
Ill do some more testing to find my problem. Also I do need 16gb allocated if imma be running 300+ mods.

**Comment by JoelZBub** [comment]
ZERO reason
