### ISSUE TITLE
[Feature Request] Strays

### ISSUE THREAD

**Issue by Akiak7** [0SoggyMustache0/ZAWA#125]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when, every time I install the mod, I have to go through the config and reduce the Min Size value for every animal to 1. This is because I just don't think it's particularly realistic that animals are ALWAYS in a pack. I think it just looks better if occasionally you can run into a single elephant rather than multiple. It's also better for performance obviously.

**Describe the solution you'd like**
Either change the default values for Min Size to 1 for all animals, or implement some kind of 'stray' spawning mechanic, that is separate from the regular packs and somewhat rarer (and obviously configurable).

**Comment by 0SoggyMustache0** [comment]
Are you not able to copy the config file from the old version into the new folder? The default values for spawns will not be changing and the reason we have the config is so if you don't like how they are you can change them to what you want. I don't understand your 'stray' mechanic either you need to elaborate.

**Comment by JoelZBub** [comment]
Just copy and paste your config from the previous version into your new version folder and let it overwrite the default.
