### ISSUE TITLE
[Feature Request] Zoo Banners

### ISSUE THREAD

**Issue by Platinum234** [0SoggyMustache0/ZAWA#128]
**Feature requests that do not follow this template will be ignored and closed**
**Do NOT suggest animals or model change**

**Is your feature request related to a problem? Please describe.**
Banners like the ones you see outside of some zoos before you get to the gates, or are in the parking lot

**Describe alternatives you've considered**
I currently plan to attempt to make something similar to what I'd like using Chisel and Bits

**Comment by kmfisk** [comment]
These would need to be big and have very specific art. Use Chisel and Bits, or make your own and use OPF.

**Comment by JoelZBub** [comment]
fisk is right. This is something that is up to the player to use the tools at their disposal to accomplish.
