### ISSUE TITLE
earlier versions of ZAWA are unplayable

### ISSUE THREAD

**Issue by dinopaul** [0SoggyMustache0/ZAWA#130]
**Issues that dont follow this template will be ignored and closed**

**Test before making a report by removing all mods except ZAWA, Bookworm and ZAWA Add-ons. Check that you are using the latest versions of these mods. Delete these lines when making a report.**

I tried to play the 1.7.0 version of ZAWA, but it crashes every time it starts loading the mod. I looked at the report, and the only thing I got out of it was something about the zookeeper not being classed right. I originally tried to play this version with older version of lil critters and natural fauna addons, as well as travelers backpack, biomes o plenty, journeymap, craftable nametags, and dynamics trees, but when the issue happened I turned off all but bookworm and ZAWA, and the problem still occurred. It may be silly of me to want to play the older versions, but I was feeling nostalgic when I watched vintagebeefs videos on the series.

To Reproduce**Steps to reproduce the behavior. (What were you doing when this happened) :
1. download ZAWA version 1.7.0 and bookworm 2.5.2.1 on twitch 
2. hit play on the modpack
3. hit play on the launcher
4. on the mod loading screen for minecraft, it will crash when when the first bar says 2/7, and the second bar says 6/6

**Expected behavior**
I expected the mods to load in normally, and I would be able to play the older version of ZAWA

**Screenshots**

** Crash Report or Game Log**
https://pastebin.com/ran0kdgi

**Please complete the following information):**
 - Mod Version Number : 1.7.0
 - Bookworm Version Number : 2.5.2.1
 - Forge Version Number : 14.23.5.2854
 - Are other mods installed? : yes, but this happens whether they are on or not
 - Is OptiFine installed? : no
 - Is this bug present in single player or on a server or both? : havent tried either, because the game crashes before i can play
 
**Additional context**
Add any other context about the problem in place of this sentence.

**Comment by 0SoggyMustache0** [comment]
Use the right bookworm with the right zawa and don't report issues unless it is for the latest version.

**Comment by dinopaul** [comment]
which is the right bookworm? because bookworm doesnt tell me

**Comment by JoelZBub** [comment]
the download page does tho

**Comment by dinopaul** [comment]
i just checked and it doesnt actually provide which version of bookworm to use
