### ISSUE TITLE
[Bug] my zawa config is not working

### ISSUE THREAD

**Issue by shonabudi** [0SoggyMustache0/ZAWA#134]
i have disabeld the poacher entiti in the config then I opened the game and it was still there

![ביאור 2020-07-04 181039](https://user-images.githubusercontent.com/67815579/86515469-b6e6d200-be21-11ea-8243-509c5a85e491.png)
 

 - Mod Version Number : 1.12.2-2.10
 - Bookworm Version Number : 1.12.2-2.5.2.1
 - Forge Version Number :1.12.2
 - Are other mods installed? : no
 - Is OptiFine installed? : no
 - Is this bug present in single player or on a server or both? : single player

**Comment by JoelZBub** [comment]
This invalid issue has been duplicated 13 times. 3 of them are yours. Don't report it again. Go back and read the closed issue.
