### ISSUE TITLE
[Bug] Game crashing before I have a chance to play.

### ISSUE THREAD

**Issue by KiraSvo** [0SoggyMustache0/ZAWA#135]
**Describe the bug**
I just downloaded the mod today and whenever I press play on the Minecraft launcher, after a few seconds of the player opening up, it crashes. 

**To Reproduce**
Steps to reproduce the behaviour. (What were you doing when this happened) :
1. Open the Minecraft Launcher
2. Press play to begin the game
3. Wait for the game to open up 
4. After a few seconds of the player opening, it crashes.

**Expected behaviour**
I expected my game to open and for me to be able to play Minecraft while using this mod.

**Screenshots**

** Crash Report or Game Log**
https://pastebin.com/MrTtWSKe

**Please complete the following information):**
 - Mod Version Number: 2.1.0
 - Bookworm Version Number: 2.5.2.1
 - Forge Version Number: 1.12.2
 - Are other mods installed? : No
 - Is OptiFine installed? : No
 - Is this bug present in single player or on a server or both? : The game crashes before I get to the main menu.
 
**Additional context**
I apologise if you've answered this before, I couldn't find anything about it.

**Comment by JoelZBub** [comment]
You have the Developer Version of the mod installed. Download the Main File from this link:
https://www.curseforge.com/minecraft/mc-mods/zoo-wild-animals-rebuild/files
