### ISSUE TITLE
[Bug] Game Crashing.

### ISSUE THREAD

**Issue by KiraSvo** [0SoggyMustache0/ZAWA#137]
**Describe the bug**
It causes the Minecraft player to crash before I can even begin playing the game.

**To Reproduce**
Steps to reproduce the behaviour. (What were you doing when this happened) :
1. Open Minecraft Launcher
2. Press play
3. Wait a few seconds for the player to open.
4. It shows a black screen and then crashes.

**Expected behavior**
I expected my game to open and continue running.

** Crash Report or Game Log**
https://pastebin.com/hWTKvW3x

**Please complete the following information):**
 - Mod Version Number: 2.1.0
 - Bookworm Version Number: 2.5.2.1
 - Forge Version Number: 14.23.5.2854
 - Are other mods installed? : No
 - Is OptiFine installed? : No
 - Is this bug present in single player or on a server or both? : I can't access that part yet.
 
**Additional context**
I had the same problem before, however, I accidentally downloaded the developer version. The problem is still continuing with the normal version.

**Comment by 0SoggyMustache0** [comment]
Stop using the development editions. You're doing the same thing as last time but for bookworm.
