### ISSUE TITLE
Beavers too fast while swimming

### ISSUE THREAD

**Issue by TheMooseIsLoose32** [0SoggyMustache0/ZAWA#14]
(does not follow template - request for minimal info by soggy)

**Describe the bug* the beaver is too fast while swimming. It's not realistic

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. Beaver swam
2.
3.
4.
More steps...

**Comment by JoelZBub** [comment]
This issue report is a great example how *not* to do a bug report. 
Thanks for putting almost zero effort into it, man.

**Comment by 0SoggyMustache0** [comment]
I asked him in Discord to just change the title. Smh joel.
