### ISSUE TITLE
Can't spawn terrestrial animals in creative mode

### ISSUE THREAD

**Issue by KevinBevin** [0SoggyMustache0/ZAWA#146]
I'm playing on the newest version of zawa (and bookworm), and I can't spawn certain animals from the mod. I have no problem with fish (salmon, blue fish, marine tang etc), but animals like bison, polar bear and elephant etc just won't spawn from the spawn eggs. I tried downgrading zawa to the "0.35" version, which does let me spawn the animals I couldn't spawn in "2.1.0". I reckon this is a bug, as I've tried deleting all other mods than zawa, and still wouldn't let me spawn them

**Comment by 0SoggyMustache0** [comment]
You didnt follow the template and this cannot be duplicated.
