### ISSUE TITLE
[Feature Request] I would like to see a thing implemented in this mod

### ISSUE THREAD

**Issue by DinoInADress** [0SoggyMustache0/ZAWA#148]
**Feature requests that do not follow this template will be ignored and closed**
**Do NOT suggest animals or model change**

**Is your feature request related to a problem? Please describe.**
Nope, just an idea

**Describe the solution you'd like**
I would love the ability to be able to paint the elephants, even if instead of being able to paint the entire animal like you can in ARK: Survival Evolved, if there were say specific regions that you could paint I would be perfectly happy with that.

**Describe alternatives you've considered**
You could instead of being able to do custom designs you could perhaps click on the elephants with a dye and it would add a painted style texture in the color of the dye. Or maybe even a special saddle for the Indian Elephants that gives them a painted look? I don’t know, I just think that it would be cool to be able to decorate the Elephants. 

**Additional context**
Add any other context or screenshots about the feature request in place of this sentence.

**Comment by 0SoggyMustache0** [comment]
A painting feature would not make sense in this mod so this will not be happening.
