### ISSUE TITLE
[Feature Request] Compatibility with Rats Mod (Raptor Food)

### ISSUE THREAD

**Issue by JoelZBub** [0SoggyMustache0/ZAWA#15]
Bald Eagles only eat ZAWA Brown Rats. It would be nice if they were predators of rats added by the Rats mod.

**Describe the solution you'd like**
Target rats:rat as food if Rats mod is installed.

**Describe alternatives you've considered**
None that I can think of.

**Comment by 0SoggyMustache0** [comment]
This feature will be present in 2.0.1
