### ISSUE TITLE
ZAWABaseLand no longer exists so I can't make a land animal

### ISSUE THREAD

**Issue by emkirsh** [0SoggyMustache0/ZAWA#151]
So, I'm coding an add-on and the wiki says to just extend the ZAWABaseLand class, but when I try that, it's still red. When I type ZAWA, some suggestions show up, including ZAWABaseWater, but still no ZAWABaseLand. This is using the latest 1.12.2 dev jars from curseforge. (ZAWA-1.12.2-2.1.0.-dev.jar and bookworm-1.12.2-2.5.2.1-dev.jar)

**Comment by 0SoggyMustache0** [comment]
The class has been changed to AbstractZawaLand and is a kotlin file. I will try to update the wiki when I can.

**Comment by emkirsh** [comment]
Ok. So, I'm not too familiar with kotlin files, but I can look it up.

**Comment by 0SoggyMustache0** [comment]
I have created a new issue template for library help. If you need anything in the future you can either open an issue with that template or you can pm me on discord.
