### ISSUE TITLE
[Feature Request] I would like to see IUCN Icons implemented in this mod

### ISSUE THREAD

**Issue by AuraBird1** [0SoggyMustache0/ZAWA#153]
**Feature requests that do not follow this template will be ignored and closed**
**Do NOT suggest animals or model change**

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Basically items you can put in item frames that have things like EX, CE, TH, LC, etc.

**Describe alternatives you've considered**
There is already a mod that has these but, with ZAWA being updated to 1.16 and the said mod probably not, I think it'd be nice to have them in there.

**Additional context**
They'd basically look like this (this is a quick little thing and can be made more fancy):
![tut3](https://user-images.githubusercontent.com/68622092/88120800-abf9a480-cb78-11ea-9307-484eb94cfac5.png)

**Comment by kmfisk** [comment]
These have been drawn up and are likely to be implemented in the future.

![image](https://user-images.githubusercontent.com/54163331/89566127-94175700-d7ed-11ea-9d19-7733c76fc870.png)

If you have the Online Picture Frames mod, you can use them in your current worlds by using the image URLs here.

https://imgur.com/a/SBBF6PZ

Thanks for your suggestion!
