### ISSUE TITLE
[Feature Request] I would like to see a thing implemented in this mod

### ISSUE THREAD

**Issue by pantsareforsquares1** [0SoggyMustache0/ZAWA#158]
**Feature requests that do not follow this template will be ignored and closed**
**Do NOT suggest animals or model change**

**Is your feature request related to a problem? Please describe.**
octopus does not show species the variant is.  when clicked on with a data book or selecting variant with spawn egg it only shows what variant and not what species

**Describe the solution you'd like**
the octopus should show what species it is when looking at what variant it is in the databook and when selecting the variant/species on the spawn egg

**Describe alternatives you've considered**
this has already been done for the macaws, rattlesnakes, treefrogs, etc. so I think it should be able to be done for the octopus as well.  

**Additional context**
personally I find it a bit annoying as there are some variants in there which I've been unable to figure out the species and can't really build for as I can't find out anything about the animal if I don't know what species it is.

**Comment by JoelZBub** [comment]
This seemed like a good request until you started whining about it being "annoying". The developer isn't here to remove your annoyances. The mod is provided as-is and without any promises of suitability for use. Learn how to make a request in the future and act like your thankful for what's been given to you.
