### ISSUE TITLE
[Feature Request] I'd like to see exhibit spawners added to ZAWA. 

### ISSUE THREAD

**Issue by mistermage1** [0SoggyMustache0/ZAWA#160]
**Feature requests that do not follow this template will be ignored and closed**
**Do NOT suggest animals or model change**

**Is your feature request related to a problem? Please describe.**
It can get frustrating when your exhibit doesn't work, animals get out, it's too small or cramped, or you can't find the right decoration. I think for a few key animals (Whales, Elephants, Hippopotamus, Giraffe, other large animals) I'd be happy to give exhibit building and design to the experts.

**Describe the solution you'd like**
In short, for more popular animals like the African/Asian Elephants, Reticulated Giraffe, Humpback Whale, etc. An item that you can place down that adds a pre-made exhibit would be nice for people who want to make a zoo but really can't build. With this you could also edit the exhibits to your liking, making the perfect exhibit for you that looks nice in your zoo.

**Describe alternatives you've considered**
While there are mods that let you copy and paste exhibits, you still have to build them first. You can follow tutorials, but those don't always give perfect results. They can be outdated, not the right size, or just plain bad. it can also be difficult to replicate exhibits from tutorials.

**Additional context**
Something akin to the Instant Structures Mod would work well with ZAWA.

**Comment by 0SoggyMustache0** [comment]
That wouldn't fit with the mod. If you want something like this find existing buildings from world downloads or other mods and use mods to add them to your world.
