### ISSUE TITLE
[Bug] Mobs do not spawn in OTG overworlds

### ISSUE THREAD

**Issue by authvin** [0SoggyMustache0/ZAWA#163]
**Issues that dont follow this template will be ignored and closed**

**Test before making a report by removing all mods except ZAWA, Bookworm and ZAWA Add-ons. Check that you are using the latest versions of these mods. Delete these lines when making a report.**

**Describe the bug**
When making an OTG world on a server, the overworld will not spawn ZAWA mobs. ZAWA mobs do spawn with the exact same setup in singleplayer, and in multiplayer they spawn in OTG dimensions if enabled in ZAWA configs, so this issue only happens when ZAWA interacts with an OTG overworld on a server. 

Could also affect other non-vanilla overworlds from other mods, but I have not tested this.

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. Make a Biome Bundle world following [these instructions](https://openterraingen.fandom.com/wiki/Installing_OTG#Forge_Installation_Instructions)
2. Load up the world, go to any vanilla biome
3. Do /otg biome -m
4. In singleplayer the list will contain ZAWA mobs, in Multiplayer it will not.

**Expected behavior**
I expected ZAWA creatures to appear in spawn lists in an OTG overworld just like they do in singleplayer with the same setup

**Screenshots**
The following are biome mob spawn lists from OTG. In the first one is a list of spawning creatures for the Mesa Plateau biome on a server. The second is the same list from the same biome, taken in singleplayer. The singleplayer screenshot is expected behaviour.

On server:
![2020-08-15_15 47 03](https://user-images.githubusercontent.com/37563355/90316466-b82c1400-df22-11ea-9e56-b0c064dca30f.png)

In singleplayer:
![2020-08-15_18 10 50](https://user-images.githubusercontent.com/37563355/90317309-c3823e00-df28-11ea-88c7-29092e58daa6.png)

** Crash Report or Game Log**
Does not crash, no info in logs

**Please complete the following information):**
 - Mod Version Number : 2.1.0
 - Bookworm Version Number : 2.5.2.1
 - Forge Version Number : 14.23.5.2847
 - Are other mods installed? : Yes
 - Is OptiFine installed? : No
 - Is this bug present in single player or on a server or both? : Only server
 
**Additional context**
A likely culprit is that an OTG overworld on a server will be world-type: OTG, instead of world-type: normal. 

There's a related OTG issue: https://github.com/PG85/OpenTerrainGenerator/issues/507

Mods installed:
- Biome Bundle v6.1
- bookwork
- OTG v8.0 and above
- ZAWA

I'm fairly certain the issue is caused by ZAWA and not OTG, though I can't be 100% sure of course. The same issue is not present with other mob-adding mods, like Mo' Creatures.

I tried setting "ZAWA overworld only spawns" to false in hopes of that fixing the issue, but there were still no spawns in the overworld.

**Comment by JoelZBub** [comment]
This is 100% caused by OTG. 
ZAWA uses the Forge Biome Dictionary to register spawnable biomes.
OTG does not register standard biomes that use the biome dictionary.
You can try configuring OTG biomes to inherit Vanilla biomes in *OTG* configs, if you're up to the task of trying to get it to work.

**Comment by authvin** [comment]
I don't know if you actually read the issue? ZAWA mobs spawn in OTG biomes that inherit from vanilla biomes just fine. The issue comes when the world is an OTG overworld, where ZAWA mobs are *not in the vanilla spawn lists*

**Comment by JoelZBub** [comment]
Paste your SpawnConfiguration configs from both your server and client to hatebin.com and share the links.

**Comment by authvin** [comment]
I have not touched that config, it's got default values
