### ISSUE TITLE
Unable to configure net properly

### ISSUE THREAD

**Issue by AechtRob** [0SoggyMustache0/ZAWA#165]
I am trying to restrict the net to capture only a selection of the entities in my modpack. This results in a very long list blacklist for the config file.... and some of these entity strings exceed the length which Forge seems to want to use. This then crashes the installation when you launch a world. The config I am using is attached here. The errors in the debug log are all around this kind of thing: "io.netty.handler.codec.DecoderException: The received string length is longer than maximum allowed (35 > 32)"

[ZAWA1.12.2-2.1.0.txt](https://github.com/0SoggyMustache0/ZAWA/files/5097724/ZAWA1.12.2-2.1.0.txt)

**Comment by JoelZBub** [comment]
Start by removing all the spaces in between lines. It's a mess

**Comment by AechtRob** [comment]
It has nothing to do with whitespaces, which are being added by Zawa/Forge itself as part of its config parsing and re-saving, not by me. But I'll re-create this issue again now, as it looks like you didn't like that I didn't use the formal template.
