### ISSUE TITLE
Poachers Everywhere!!!

### ISSUE THREAD

**Issue by BetterToBeBloody** [0SoggyMustache0/ZAWA#166]
**Describe the bug**
Ever since I have downloaded this mod, there have been so many poachers, like 20 within a few blocks of each other. There are so many and no way to decrease the issue.

**To Reproduce**
1. Downloaded the mod.
2. Loaded up a new world and there were a bunch of poachers.
3. Looked to see if there was a way to turn the spawn rate down, there isn't.
4. Loaded a new world to see if it was just that one world, it is not. 

**Expected behavior**
I would like there it either be a decrease in the amount of poachers, or the ability to decrease the population.

**Screenshots**
I do not have screenshots.

** Crash Report or Game Log**
Game did not crash.

**Please complete the following information):**
 - Mod Version Number : 1.12.2-2.1.0
 - Bookworm Version Number : 1.12.2-2.5.2.1
 - Forge Version Number :1.12.2
 - Are other mods installed? : Yes, I do have a lot of other mods.
 - Is OptiFine installed? : No.
 - Is this bug present in single player or on a server or both? : I have not been on the server yet, so I believe it is just part of the single player option. 
 
**Additional context**
I don't have anything else really to say. 

Thank you to anyone who reads this bug report.

**Comment by 0SoggyMustache0** [comment]
Look at the other posts of this same "bug" that doesn't exist
