### ISSUE TITLE
poachers overpopulating world

### ISSUE THREAD

**Issue by knzcali** [0SoggyMustache0/ZAWA#169]
is there a config file i can edit to turn off poacher spawning? theyre absolutely overrunning the world and its really annoying

**Comment by knzcali** [comment]
nevermind lol

**Comment by JoelZBub** [comment]
yeahhhhhhh.....

**Comment by JoelZBub** [comment]
Duplicate of
#166 #134 #133 #132 #92 #90 #81 #77 #76 #52 #50 #46 #29 #28
