### ISSUE TITLE
[Bug] Humpback Whale and Hawksbill Sea Turtle Spin in Place

### ISSUE THREAD

**Issue by Seralii** [0SoggyMustache0/ZAWA#17]
**Describe the bug**
Humpback whale and Hawksbill Sea Turtle spin rapidly and almost constantly in water.

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. Spawned Humpback whale and Sea Turtle (multiple)
2. All whales and Sea Turtles spin in place (not at the same time)

**Expected behavior**
Swim smoothly and naturally.

**Please complete the following information):**
 - Mod Version Number : 1.12.2-2.0.0
 - Bookworm Version Number : 1.12.2-2.5.0
 - Forge Version Number : 14.23.5.2847
 - Is OptiFine installed? : Yes
 - Is this bug present in single player or on a server or both? : Singleplayer (have not tested multiplayer)

**Comment by 0SoggyMustache0** [comment]
Fixed for 2.1.0
