### ISSUE TITLE
[Library Change] I would like to see this implemented into the zawa base

### ISSUE THREAD

**Issue by BotCpu** [0SoggyMustache0/ZAWA#173]
an setting to change animals spawn rate
too many animals on screen reduces performance on low-end pcs

**Comment by JoelZBub** [comment]
This is quite possibly the worst issue report ever, for the following reasons:
1. It did not follow the template provided.
2. It was a request for a feature that has been part of the game for **years**.
3. The title had nothing to do with the actual request.
