### ISSUE TITLE
[Feature Request] The drinking system.

### ISSUE THREAD

**Issue by Tuckamore** [0SoggyMustache0/ZAWA#174]
I’ve been frustrated with the water/dehydration system, an animal will take one drink from the cauldron and it will immediately drain, and it won’t actually work to stop their thirst. They also have been dying because they don’t seek out water/actually drink it, I have an entire pride of lions in my zoo die from dehydration as well as some coatimundi.

Putting a better drinking system in place, or updating the AI so they actually seek out and drink water.

Maybe have it so they don’t immediately drain the cauldron of water? It’s just annoying to have to spam-click the cauldron with a bucket of water and still have the lion drinking it die on me.

Sorry if this is something that is already being worked on or if it’s just a glitch in my game.

**Comment by JoelZBub** [comment]
Change the thirst values/rates  in your configs or disable this feature if you don't like this.
