### ISSUE TITLE
[Possible Bug] ZAWA blocking Animania mobs from spawning.

### ISSUE THREAD

**Issue by JNarh** [0SoggyMustache0/ZAWA#179]
Added ZAWA and its requirements to a server (version 1.12.2) That was going through a wipe + new map. We added mods one at a time, testing them as we go and everything was fine until we added ZAWA.  Mobs from Animania stopped spawning Naturally.  Removing ZAWA enables those mobs to resume spawning in new chunks only. The server owner and several players tested on single player and said that ZAWA mobs dominated the landscape and Animania mobs were extremely few and far between (. cutting the spawn rates down for ZAWA and starting a new map did not seem to help any.

The mods work fine on their own with the rest of the mods, but when I add both, ZAWA seems to override Animania
I've used both these mods alongside eachother before with no issues, as Animania replaces vanilla animals, so i dont know what the issue might be. There are no errors, crashes, or anything that shows up in logs of the server console.

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. Added Animania and made sure it was running
2. Added ZAWA
3. Mobs from Animania vanished
4. Created a new world and still no Animania mobs
5. Removed ZAWA and Animania mobs started spawning again

**Expected behavior**
Expected both mobs to play nice with eachother

**Please complete the following information):**
 - Mod Version Number :
1.12.2-2.1.0
 - Bookworm Version Number :
1.12.2-2.5.2.1 
 - Forge Version Number :
14.23.5.2854 (recommended build for 1.12.2)
 - Are other mods installed? : 
Animania + its requirements
T-Construct
Champions
A dungeon generator 
Lootbags
Archeology
 - Is OptiFine installed? : 
Optifine on client side
 - Is this bug present in single player or on a server or both? :
Both

**Comment by JoelZBub** [comment]
This is not an issue. 
You need to configure the spawn rates of animania and zawa to be balanced according to your needs.

**Comment by JoelZBub** [comment]
Animania has spawn chances set around 7 to 8.
Adjust ZAWA to have a similar spawn chance or raise animania's spawn chance to match ZAWA's if you want these mods together.
Note, too, that animania sets a cap on the number of each type that can spawn.
