### ISSUE TITLE
Shows this when opening minecraft with other mods

### ISSUE THREAD

**Issue by Chickygamecube** [0SoggyMustache0/ZAWA#18]
**Issues that dont follow this template will be ignored and closed**

**Test before making a report by removing all mods except ZAWA, Bookworm and ZAWA Add-ons. Check that you are using the latest versions of these mods. Delete these lines when making a report.**

**Describe the bug**
I was very excited to add the new mobs to my world, especially the birds in my aviary world except when I start the mod with other mods with it, it just crashes. I'm very confused and Im curious whats going on. I have the zawa addons too like Nautral fauna, and better animals plus, but I'm not sure if that works either, Taking away biomes of plenty doesn't work either. 

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1.
2.
3.
4.
More steps...

**Expected behavior**
Having mobs with other mods to make a zoo and big aviary 
**Screenshots**
![Screenshot (206)](https://user-images.githubusercontent.com/62624433/77480177-76b59380-6dde-11ea-8ced-ac9c92ef9494.png)

** Crash Report or Game Log**
I dont know how to use paste bin so I apologize for showing the report on here
Error: java.lang.NoSuchMethodError: org.zawamod.util.SpawnUtils.mergeBiomes([Lnet/minecraft/world/biome/Biome;[Lnet/minecraft/world/biome/Biome;)[Lnet/minecraft/world/biome/Biome;
**Please complete the following information):**
 - Mod Version Number : Zawa.1.12.2.2.0.0
 - Bookworm Version Number : bookworm-1.12.2-2.5.0 
 - Forge Version Number : 14.23.5.2846
 - Is OptiFine installed? : yes
 - Is this bug present in single player or on a server or both? : I don't use servers so single. 
 
**Additional context**
Im not sure if I have to use Zawa dev for mod mob problems but any help will do, also thank you for  taking your time reading this and hope it helps.

**Comment by 0SoggyMustache0** [comment]
This is invalid and provides no information.
