### ISSUE TITLE
[Bug] Doors not aligned with their fence counterparts

### ISSUE THREAD

**Issue by Barcawastaken** [0SoggyMustache0/ZAWA#182]
**Issues that dont follow this template will be ignored and closed**

**Test before making a report by removing all mods except ZAWA, Bookworm and ZAWA Add-ons. Check that you are using the latest versions of these mods. Delete these lines when making a report.**

**Describe the bug**
When placing down any door from ZAWA (e.g. powder door) next to a powder fence, they don't connect or align on the block. This goes for all the doors with their fences.

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. I placed a wall of any ZAWA fence.
2. I broke two blocks and placed the door

**Expected behavior**
I expected the door to be aligned with the fence.

**Screenshots**

![Screen Shot 2020-10-25 at 7 21 33 PM](https://user-images.githubusercontent.com/67441390/97121803-627ca080-16f7-11eb-83e6-750723e55675.png)
![Screen Shot 2020-10-25 at 7 21 29 PM](https://user-images.githubusercontent.com/67441390/97121808-6b6d7200-16f7-11eb-9d9e-48abe80649c7.png)

** Crash Report or Game Log**
Nothing here

**Please complete the following information):**
 - Mod Version Number : 2.1.0
 - Bookworm Version Number : 2.5.2.1
 - Forge Version Number : 14.23.5.2854
 - Are other mods installed? : Yes, I have a lot of them. If you want a list:
[Backport] 1.13 Water Mechanics [Bubble Columns] by xFrah
Abyssal Depths
Ani-Mod
Animania Base
ArchitectureCraft - TridentMC version
Better animals plus
Bibliocraft
BOP
Bookworm
Butterflys
Chisel
Chisel and Bits
ConnectedTexturesMod
Craftstudio API
Custom Mob Spawner
Custom NPCs
Dynamic trees for:
- Vanilla
- BOP
- Natura
- Pam's Harvestcraft
- Plants(the megapack by Shadows_of_Fire)
Exotic Birds
Ferdinand's Flowers
F&A Revival
Hwyla
JEI
Lil Critters
LLibrary
MalisisCore
MalisisDoors
Mantle
Mo Creatures
Natura
Pam's Harvestcraft
Placebo (Shadows_of_fire)
Plant megapack (I have both of them, one by shadows_of_fire and one by 10paksmods)
Project: Vibrant Journeys
The Birdwatching Mod
ZAWA
Zoocrafting Discoveries
 - Is OptiFine installed? : No
 - Is this bug present in single player or on a server or both? : Both
 
**Additional context**
No additional context to add.

**Comment by Barcawastaken** [comment]
this is probably more of a feature suggestion than a bug

**Comment by JoelZBub** [comment]
This would be the same as asking for vanilla doors to align with vanilla fences or glass. 
This matches vanilla behavior.
