### ISSUE TITLE
[Bug] Every animal is invisible.

### ISSUE THREAD

**Issue by moosehouse20** [0SoggyMustache0/ZAWA#184]
**Describe the bug**
Every animal is invisible, I can't see any animals that are in this mod, but I can see the poachers

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
I was looking at the animals in this mod but they were invisible

**Expected behavior**
I expected to see the animals.

**Screenshots**
![2020-10-27_20 20 52](https://user-images.githubusercontent.com/58569379/97354636-fdab7c80-1895-11eb-8e32-75d9bb1b584c.png)

** Crash Report or Game Log**
My game did not crash
**Please complete the following information):**
 - Mod Version Number: 1.12.2-2.1.0
 - Bookworm Version Number: 1.12.2-2.5.2.1
 - Forge Version Number: 1.12.2-14.23.5.2854
 - Java Version Number: Version 9 Update 271 (build 1.8.0_271-b09)
 - Are other mods installed? : Yes
The mod works if I remove all my other mods but whit my other mods enabled it doesn't work
My mods:
AI Improvements
AlcatrazCore
Aquaculture 2
AutoRegLib
Better Animal Models
Better Animals Plus
BetterFps
Biomes O'Plenty
Bookworm
CoroUtil
CraftStudio API
Custom Mob Spawner
Dynamic Surroundings
Dynamic Trees
Familiar Fauna
iChunUtil
Just Enough Items
LLibary
Macaw's Bridges
Mo'Creatures
Neat
No Tree Punching
OreLib
Quark
Rikmulds Core Mod
Shadowfacts'Forgelin
Spartan Compatibility
Spartan Shields
Spartan Weaponry
Tough As Nails
ZAWA
 - Is OptiFine installed? : Yes
 - Is this bug present in single player or on a server or both? : Single-player

*And yes I do have the latest version of bookworm and zawa so don't yell at me*

**Comment by JoelZBub** [comment]
Figure out which mod is doing this and remove it.

**Comment by JoelZBub** [comment]
Since I'm an amazing person, I'm going to tell you the problem.

Set `I:enableLatchedRendererSpawn=0` in ichunutils.cfg
