### ISSUE TITLE
[Bug] Orca cannot be tamed or clicked on with the animal data book

### ISSUE THREAD

**Issue by OrangePineapple1** [0SoggyMustache0/ZAWA#185]
**Issues that dont follow this template will be ignored and closed**

**Describe the bug**
Orcas cannot be tamed or clicked on with the animal data book. All that happens when I right click is the produce bubbles form the blowhole

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. Spawn an orca
2. Get animal data book
3. Right click the orca
4. The orca information does not come up, it only make bubbles
More steps...

**Expected behavior**
Orca can be tamed and clicked on

**Screenshots**

** Crash Report or Game Log**
If your game crashed, paste your crash report to https://pastebin.com/ or similar service and paste the link in place of this sentence.

**Please complete the following information):**
 - Mod Version Number : 2.0.0
 - Bookworm Version Number : 2.5.0
 - Forge Version Number : 14.23.5.2854
 - Are other mods installed? : Only Zawa addons
 - Is OptiFine installed? : No
 - Is this bug present in single player or on a server or both? : Only tried on single player
 
**Additional context**
Please respond with what I can do to fix this as I have noticed many issues are being ignored.

**Comment by JoelZBub** [comment]
Update ZAWA

**Comment by OrangePineapple1** [comment]
I can't update zawa because then the addons won't work.

**Comment by JoelZBub** [comment]
And you can't figure out why issues go ignored and the lead dev got sick of working on this mod and quit...

**Comment by OrangePineapple1** [comment]
Um, excuse me? I didn't do anything wrong. I don't appreciate your attitude when all I was trying to do was get some help.

**Comment by JoelZBub** [comment]
You: "Please respond with what I can do to fix this..."
Me: "Update your mod"
You: "no"

You received the help you requested and refused it.

**Comment by OrangePineapple1** [comment]
No, I did try to update the mod. The addons will not work with newer version.
