### ISSUE TITLE
[Bug] Crash when using data book on animals with Architecturecraft - TridentMC Version loaded

### ISSUE THREAD

**Issue by APerson7** [0SoggyMustache0/ZAWA#19]
**Describe the bug**
Minecraft will crash when one right clicks on a ZAWA (or addon) creature with the Data Book. This occurs only when the mod "Architecturecraft - TridentMC Version" is loaded alongside ZAWA. I have tested this on an instance with the only mods being ZAWA, Bookworm, and "Architecturecraft  - TridentMC Version." Removing Architecturecraft stops all crashes with this method.

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. Install ZAWA, Bookworm, and "Architecturecraft - TridentMC Version" on the latest version of forge for 1.12.2 
2. Launch the game
3. Enter any singleplayer world
4. Attempt to use the Data Book on any creature from ZAWA or one of its addons

**Expected behavior**
Expected data book GUI to open without issue.

**Screenshots**
With Architecturecraft:
![2020-03-24_15 21 15](https://user-images.githubusercontent.com/53496153/77486019-e8480e80-6deb-11ea-8c9b-1c8d53dcf512.png)

![Screenshot (7)](https://user-images.githubusercontent.com/53496153/77486092-0877cd80-6dec-11ea-9992-31418292a891.png)

Without Architecturecraft:
![2020-03-24_16 27 03](https://user-images.githubusercontent.com/53496153/77486190-52f94a00-6dec-11ea-8d3e-b19545d96742.png)

** Crash Report or Game Log**
No Vanillafix: https://pastebin.com/7QPMw9F7
With Vanillafix: https://pastebin.com/EPLJcWkb

**Please complete the following information):**
 - Mod Version Number : 2.0.0
 - Bookworm Version Number : 2.5.0
 - Forge Version Number : 14.23.5.2847
 - Is OptiFine installed? : No
 - Is this bug present in single player or on a server or both? : Singleplayer, though I have no means of testing in a server environment

 
**Additional context**
VanillaFix was used only to visualize a crash occurring, as the crash still happens without it. I have linked crash reports both with and without VanillaFix.
Link to Architecturecraft - TridentMC Version: https://www.curseforge.com/minecraft/mc-mods/architecturecraft-tridev
The version of Architecturecraft that I used was as follows: 3.98

**Comment by 0SoggyMustache0** [comment]
ZAWA 2.0.1 has just released. Please try that and then leave a comment if the issue persists.

**Comment by APerson7** [comment]
I can confirm that the bug has been fixed, and that no more crashes with Architecturecraft occur.
