### ISSUE TITLE
[Bug] Spawns are still double registering

### ISSUE THREAD

**Issue by jmlwhittington** [0SoggyMustache0/ZAWA#193]
**Describe the bug**
Spawns are still registering twice, according to [TellMe](https://www.curseforge.com/minecraft/mc-mods/tellme) output (/tellme dump-csv biomes-with-mob-spawns). I see in 2.0.1, this was said to have been fixed, but I am still seeing it even when these are the only mods installed.

**To Reproduce**
1. Perform a clean install
2. Place Bookworm, ZAWA, and [TellMe](https://www.curseforge.com/minecraft/mc-mods/tellme) in the mods folder
3. Start a world
4. Run command /tellme dump-csv biomes-with-mob-spawns
5. Investigate output file

**Expected behavior**
Spawns should only be registering once.

**Please complete the following information):**
 - Mod Version Number: 2.0.35 & 2.1.0
 - Bookworm Version Number: 2.5.2.1
 - Forge Version Number: 14.23.5.2854
 - Are other mods installed?: Only [TellMe](https://www.curseforge.com/minecraft/mc-mods/tellme)
 - Is OptiFine installed?: No
 - Is this bug present in single player or on a server or both?: Only tested on single player, but likely also relevant on server
 
**Additional context**
Comparing to vanilla spawns or other mods that introduce new spawns will display expected behavior of one registered spawn per mob per biome.

**Comment by JoelZBub** [comment]
But who cares, really? 
How does this affect anything other than not having a clean printout for your OCD?

**Comment by jmlwhittington** [comment]
@JoelZBub Um...one would assume it having been in the changelog at some point in time, it came up on the radar for some reason, even if it was just because it was easily solvable. I was just highlighting that it was not the case that it was fixed. I don't have OCD and I don't understand your attitude. It would have been just as easy to have ignored it, as you have apparently done for other reported issues.

**Comment by 0SoggyMustache0** [comment]
This is intentional to fix issues where the animal finding book cannot show what animals spawn where when the player is connected to a dedicated server.

**Comment by JoelZBub** [comment]
**BAHAHA**
