### ISSUE TITLE
[Bug] A thing does some other thing when a thing is doing something.

### ISSUE THREAD

**Issue by Naeski** [0SoggyMustache0/ZAWA#2]
**Issues that dont follow this template will be ignored and closed**

**Test before making a report by removing all mods except ZAWA, Bookworm and ZAWA Add-ons. Check that you are using the latest versions of these mods**

**Describe the bug**
I was trying to change my config. settings for my animals depreciation rates and when I did my game completely slowed down. It didn't crash or anything just dropped my fps down bad.

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. I previously turned the death off 
2. I then continued building my zoo (I was building an aquarium at the time)
3. I opened config. and turned it back on 
4. I then turned the last depreciation numbers to 1
5. My game slowed down and still didn't fix itself when I returned the setting to normal

**Expected behavior**
I just expected the settings to change so that my animals would eat but wouldn't die from lack of food nor enrichment 

**Screenshots**
It's more of a visual movement issue

** Crash Report or Game Log**
Game didn't crash from this

**Please complete the following information):**
 - Mod Version Number : 1.12.2-2.0.0
 - Bookworm Version Number : 1.12.2-2.5.0
 - Forge Version Number : 1.12.2-14.23.5.2847
 - Is OptiFine installed? : Yes

**Additional context**
I'm not completely sure if it's my computer or just cause the mod is fairly new. I don't want to get rid of all my work so it'd be great if there was a way to fix this without me having to redo everything

**Comment by 0SoggyMustache0** [comment]
So you set the config value for depreciation of each stat to be 1?

**Comment by Naeski** [comment]
Yes. So if it said 9.0E-4 I replaced the 4 with a 1

**Comment by 0SoggyMustache0** [comment]
That would have cause the animals stats to go down much quicker. 9.0E-4 is 0.00009 and 9.0E-1 is 0.09 (my numbers may be off by one decimal but you get the point). Chances are the lag came from your animals rapidly losing stats and then the particles and word changes from them trying to save themselves.

**Comment by Naeski** [comment]
Oh no. I see. I’m horrible at math and stuff like that so I didn’t realize.
Yea you’re most likely right. Thank you. Do you have any suggestions on how
to fix it or should I just kinda play around with it and see what works?

**Comment by 0SoggyMustache0** [comment]
I would suggest that you add to the 4 if you want it to be slower. You can press F3 before you open the data book and see the floating point value of animal stats on the left side so that could help you find a value you want. If you want to disable stat lowering then use the option made for that.

**Comment by Naeski** [comment]
Alright. Thank you so much you’ve been a big help. I’m sorry I bothered you
with something like this. You probably think it’s stupid 😅
