### ISSUE TITLE
Hello this site does not have fully accurate recipes do not trust this site as it is basically just to harbor there minecraft mod fan chat which is slightly toxic and shuts you down and makes you wait on a 2 hour mute just to talk to someone for maybe some direction or aid in finding the recipes you will have better luck installing jei or finding them though files if you use this mod which is sad becouse all other mods I've ever seen have accurate recipes and wikis, I am useing the 1.12.2 version of this mod with the second set of animals too hope this helps the unknowing player or mod here as this wiki is very sad

### ISSUE THREAD

**Issue by The-artwoolf** [0SoggyMustache0/ZAWA#217]
**Feature requests that do not follow this template will be ignored and closed**
**Do NOT suggest animals or model change**

**Is your feature request related to a problem? Please describe.**
Replace this sentence with a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
Replace this sentence with a clear and concise description of what you want to happen.

**Describe alternatives you've considered**
Replace this sentence with a clear and concise description of any alternative solutions or features you've considered. Are other mods able to do what you are suggesting?

**Additional context**
Add any other context or screenshots about the feature request in place of this sentence.

**Comment by gkazan** [comment]
Wtf?

**Comment by JoelZBub** [comment]
This is why modding is not fun. This right here.

**Comment by BuzzfeedBlue** [comment]
useing

**Comment by Coda1552** [comment]
> Wtf?

This guy is trying to say that this site does not have fully accurate recipes do not trust this site as it is basically just to harbor there minecraft mod fan chat which is slightly toxic and shuts you down and makes you wait on a 2 hour mute just to talk to someone for maybe some direction or aid in finding the recipes you will have better luck installing jei or finding them though files if you use this mod which is sad becouse all other mods I've ever seen have accurate recipes and wikis, I am useing the 1.12.2 version of this mod with the second set of animals too hope this helps the unknowing player or mod here as this wiki is very sad
