### ISSUE TITLE
[Bug] Mobs don't spawning on server

### ISSUE THREAD

**Issue by TobiasMJC** [0SoggyMustache0/ZAWA#22]
**Describe the bug**: I'm playing a modpack with zawa, there are 2 friends with me. But we walked 2.000 blocks and we didn't saw any mob, I tried it on singleplayer and it worked perfectly. (The config are the same in both)

**To Reproduce Steps**: 1. I tested all the mods in singleplayer and I saw so many zawa mobs
2. When I played with my friends in multiplayer, I didn't see any mob

**Expected behavior**: I don't know, I only know it's not the config

**Screenshots**: I think is not necessary

Mod Version Number : 2.0.1
Bookworm Version Number : 2.5.0
Forge Version Number : 1.12.2 (2847)
Is OptiFine installed? : Yes
Is this bug present in single player or on a server or both? um, I think I explained that. XD

**Comment by 0SoggyMustache0** [comment]
Provide more information.

**Comment by TobiasMJC** [comment]
> Provide more information.

More information? that's all I've got.

**Comment by 0SoggyMustache0** [comment]
We are unable to replicate this and can't help you in that case. Try deleting your configs.

**Comment by JoelZBub** [comment]
I may have duplicated this issue but need a modlist to confirm possible mod conflicts.
