### ISSUE TITLE
The gharial has too fast an animation and walk speed

### ISSUE THREAD

**Issue by TheMooseIsLoose32** [0SoggyMustache0/ZAWA#25]
**Issues that dont follow this template will be ignored and closed**

Proven without any other mods. Also by soggy's stream

Whenever the gharial walks, the walking animation and speed is quite high. And it should be slowed down to be more realistic

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. Spawned a ZAWA gharial
2. Had the gharial walk in an open space

**Expected behavior**
The gharial should have a slowed animation and walking speed to make it more realistic

**Screenshots**
Not applicable

** Crash Report or Game Log**
None

**Please complete the following information):**
 - Mod Version Number : 2.0.1
 - Bookworm Version Number : 2.5.0
 - Forge Version Number : can't say for certain, but it's the latest one as of March 30th for 1.12.2
 - Is OptiFine installed? : Yes
 - Is this bug present in single player or on a server or both? : Both
 
**Additional context**
This isn't a mod issue as much as it is a realism issue. Everyone has it and can replicate the issue

**Comment by 0SoggyMustache0** [comment]
This change will be present in zawa 2.1.0
