### ISSUE TITLE
The zawa giant salamander should have an updated animation, model, and texture.

### ISSUE THREAD

**Issue by TheMooseIsLoose32** [0SoggyMustache0/ZAWA#26]
I'm frustrated by the model and texture of the giant salamander in zawa. The giant salamander in the newest version of zawa 2.0.1 is not up to date with the rest of the models, and I, along with many others, can agree that a remodel and retexture would be awesome to see. No other mod adds this magnificent creature, so I ask the zawa team for a revamped giant salamander. As far as images go I couldn't figure out how to add them. But as seen from the mod, the salamander could use some updating. Thank you!

**Comment by 0SoggyMustache0** [comment]
While your reasons make sense I cannot control what models get changed or if they do. I believe there are plans for more model changes to animals in the future but can't give out much information to keep the surprise element of our releases.
