### ISSUE TITLE
[Bug] Continuous error

### ISSUE THREAD

**Issue by kaiserdj** [0SoggyMustache0/ZAWA#27]
**Describe the bug**
I have the latest version of the mods and when new chunks are being generated. At some point, an entity is randomly generated that causes minecraft to freeze at 0 fps and drop continuous error messages on the console.
It has generated a log file of more than 300 mb, the minecraft is open 5 minutes to see if it was defrosted, but I end up crashing
![image](https://user-images.githubusercontent.com/5487950/78079615-bbc46180-73ac-11ea-948d-f53d33ffeb07.png)
I will not upload the log file because it takes up too much, but it is still the same text millions of times repeated
![image](https://user-images.githubusercontent.com/5487950/78079662-d696d600-73ac-11ea-878d-5a1d93da24c9.png)

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. Start a server with the mod
2.Enter and travel the world generating chunks until it crashes

**Expected behavior**
The minecraft remains freezing(0 fps), releasing the same error in the console, continuously until it crashes

**Screenshots**
![image](https://user-images.githubusercontent.com/5487950/78079662-d696d600-73ac-11ea-878d-5a1d93da24c9.png)
![image](https://user-images.githubusercontent.com/5487950/78079615-bbc46180-73ac-11ea-948d-f53d33ffeb07.png)

** Crash Report or Game Log**
https://pastebin.com/raw/W9BMMBx9

**Please complete the following information):**
 - Mod Version Number : zawa-1.12.2-2.0.1.jar
 - Bookworm Version Number : bookworm-1.12.2-2.5.0.jar
 - Forge Version Number : 14.23.5.2838
 - Is OptiFine installed? : No
 - Is this bug present in single player or on a server or both? : server
 
**Additional context**
I don't know what else I can say, or what else can help

**Comment by 0SoggyMustache0** [comment]
I have had this happen but never had the console point to any of my classes. I know this issue is present and will take a look at the sloth since that's where yours points. Thank you.

**Comment by kaiserdj** [comment]
If I disable it, in the ZAWA configuration, it would stop having those problems, right?
![image](https://user-images.githubusercontent.com/5487950/78357625-137fea00-75b2-11ea-9576-4b5efe359cff.png)

**Comment by JoelZBub** [comment]
not if it's related to an entity already spawned in the world.

**Comment by kaiserdj** [comment]
But if you created a new world, you would no longer have that problem. A major, if the mod is updated correcting that bug, I re-enable it and they would come out again in this new world, right?

**Comment by JoelZBub** [comment]
Please clarify your question.

**Comment by kaiserdj** [comment]
The mod has a bug with the sloths, so if I disable spawn in the world, it will stop giving those problems.
The question is, if the mod is updated to correct that bug and I activate the sloth spawn, do I have to generate a new world or is it not necessary?

**Comment by JoelZBub** [comment]
Disabling that is not going to fix the problem in your already generated world if the bugged entity is already there. You have to remove the bugged entity first.

**Comment by 0SoggyMustache0** [comment]
This has been fixed for zawa 2.0.32, please update. If you find that the latest version did not fix the issue please let us know.
