### ISSUE TITLE
[Bug] Poachers Spawn in large groups?

### ISSUE THREAD

**Issue by Scinta** [0SoggyMustache0/ZAWA#28]
**Issues that dont follow this template will be ignored and closed**

**Test before making a report by removing all mods except ZAWA, Bookworm and ZAWA Add-ons. Check that you are using the latest versions of these mods. Delete these lines when making a report.**

**Describe the Bug**
I wanted to play on super flat, but when I spawned in the world, there were huge amounts of poachers, literally I couldn’t walk 9 blocks with there being at least 4 poachers randomly spawned. Is this normal? I’ve tried everything to figure it out, playing with just this mod (and the other mod it needs) same thing. 

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1.I started up a super flat world
2.I flew around
3.tons of poachers spawned at once
4.
More steps...

**Expected Behavior**
I thought having a super flat world there would be a couple of poachers every now and again, maybe some animals, but With all the poachers I couldn’t build anything without them spawning in the building. 

**Screenshots**

** Crash Report or Game Log**
If your game crashed, paste your crash report to https://pastebin.com/ or similar service and paste the link in place of this sentence.

**Please complete the following information):**
 - Mod Version Number : 1.12.2
 - Bookworm Version Number : 1.12
 - Forge Version Number : 1.12.2
 - Is OptiFine installed? : Yes.
 - Is this bug present in single player or on a server or both? : Single player.
 
**Additional Context**
So I saw this mod and decided I wanted to build a zoo. I had started on my zoo a few days ago, there were barely any poachers, then today, I go in and there are tons of poachers, in my animal habitats killing my animals.

**Comment by 0SoggyMustache0** [comment]
Config exists for a reason. Use it.

**Comment by ajith2005** [comment]
I have the same problem and i disabled mob spawning
