### ISSUE TITLE
[Feature Request] Tranq to Catch Animal Config Option

### ISSUE THREAD

**Issue by Mnesikos** [0SoggyMustache0/ZAWA#33]
**Feature requests that do not follow this template will be ignored and closed**

**Is your feature request related to a problem? Please describe.**
Hard to find spider eyes when playing this mod in peaceful mode, which are required to craft the tranquilizer ammo.

**Describe the solution you'd like**
The ability to turn off "animals need to be tranqued to be netted" in the config.

**Describe alternatives you've considered**
Could use craft tweaker to change the recipe of the ammo, but this would be a nice feature nonetheless.

**Additional context**
N/A

**Comment by 0SoggyMustache0** [comment]
Feature will be present in zawa 2.1.0
