### ISSUE TITLE
Baby Animals take damage with 1 block high

### ISSUE THREAD

**Issue by Shatter0Ice** [0SoggyMustache0/ZAWA#35]
Baby animals such as Moose, American Bison and Okapi can fit in 1 block high (sry for my english) but take damage.

Steps to reproduce the behavior. (What were you doing when this happened) :

I was playing in my survival game when suddendly I saw a baby Moose passing through a "1 block high area" and taking damage so I decided to check it in creative and it did do the same, also with the Okapi and Bison.

**Expected behavior**
Maybe they shouldn't fit in 1 block but two instead? Meaning it shouldnt be able to pass through a 1 block high area.

 - Mod Version: 1.12.2 - 2.0.1
 - Bookworm Version Number: 2.5.0
 - Forge Version Number: 2838

**Comment by 0SoggyMustache0** [comment]
I have duplicated and fixed this issue. The fix will be in 2.1.0. Are there any other animals this happens on that you are aware of?

**Comment by Shatter0Ice** [comment]
Ok I tried every animal (excluding npcs and water mobs) and with the baby zebra it happens the same. I also noticed that large animals such as giraffes and elephantes dont take damage in a 1 block high area but if u increase the number of blocks up to 2 they do take damage(instead of one block above, two or more). < I cant really say if thats a bug or just minecraft honestly.

**Comment by 0SoggyMustache0** [comment]
Thank you. As much as can be fixed will be fixed for 2.1.0
