### ISSUE TITLE
[Feature Request] Plant Data Book

### ISSUE THREAD

**Issue by Mnesikos** [0SoggyMustache0/ZAWA#36]
**Feature requests that do not follow this template will be ignored and closed**

**Is your feature request related to a problem? Please describe.**
We just wanna know where to find all the cool new plants yo

**Describe the solution you'd like**
Either a new book about the plants (could contain really cool information like the 3rd page of the data book) and where they spawn, or just adding them to the exploration guide would be nice.

**Describe alternatives you've considered**
Obviously just uninstalling zawa is the best alternative to this.

**Additional context**
pretty plants

**Comment by 0SoggyMustache0** [comment]
This feature has been added to zawa 2.1. The ability for add-on devs to add custom pages to the data book has also been added through ZAWAMain$registerBookContent(Class, BookContent)
