### ISSUE TITLE
[Feature Request] I would like seine nets to wield more feed when used

### ISSUE THREAD

**Issue by VakyPanda** [0SoggyMustache0/ZAWA#37]
**Feature requests that do not follow this template will be ignored and closed**

**Is your feature request related to a problem? Please describe.**
Whenever I use the seine net it wields low amounts of food ( Shrimp and Mussels) so I have to make many seine nets and fish for long periods of time

**Describe the solution you'd like**
I would like the seine nets to be more bountiful when fishing with them so that providing food for the filter feeders is easier.

**Describe alternatives you've considered**
Due to the enormous amount of string needed to create so many seine nets the wool into string mod has been a great advantage

**Additional context**
N/A

**Comment by 0SoggyMustache0** [comment]
Good suggestion. This will be present in zawa 2.1
