### ISSUE TITLE
[Bug] Vehicles can be duped using animal nets

### ISSUE THREAD

**Issue by VakyPanda** [0SoggyMustache0/ZAWA#38]
**Issues that dont follow this template will be ignored and closed**
**Describe the bug**
The off road vehicle can be duped using animal nets if you left click on them. ZAWA:Rebuilt Mod

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. Left clicked trying to catch animal
2.Missed and left clicked the vehicle
3.Vehicle stayed however net was filled with another vehicle
4. I placed down the other vehicle and now I had two!

**Expected behavior**
I expected/expect the vehicle to go in the net instead of duping

**Screenshots**
N/A
** Crash Report or Game Log**
Did not crash

**Please complete the following information):**
 - Mod Version Number : 2.0.1
 - Bookworm Version Number : 2.5.0
 - Forge Version Number :14.23.5.2847
 - Is OptiFine installed? : Yes
 - Is this bug present in single player or on a server or both? : Was only documented in single player
 
**Additional context**
N/A

**Comment by 0SoggyMustache0** [comment]
I am unable to duplicate this. Vehicle code has been changed for 2.1 so I assume that this is fixed unless you can provide more information on how I can try duplicating it.

**Comment by VakyPanda** [comment]
Try "catching" the vehicle like you would with a normal animal and see if it will appear in the net. If it does not  " Duplicate " then I assume its fixed.

**Comment by 0SoggyMustache0** [comment]
Yeah, thats what I did. I'll assume that everything is ok, if you update to 2.1 and it happens again please let me know. Thank you for the report.
