### ISSUE TITLE
[Bug] Birds turning into Rockets going to moon

### ISSUE THREAD

**Issue by MLGMagicHoodini** [0SoggyMustache0/ZAWA#4]
**Describe the bug**
When a bird is flying and the roof above it is removed it will continue go up forever

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1.Had a box (with roof and walls and floor)
2.Spawned some toucans
3.Then used WorldEdit to remove a wall and roof to let then free

**Expected behavior**
They should just fly normally instead of going up forever until they out of sight

**Please complete the following information):**
 - Mod Version Number : 2.0.0
 - Bookworm Version Number : 2.5.0
 - Forge Version Number : 2846
 - Is OptiFine installed? : Yes

**Comment by 0SoggyMustache0** [comment]
This is a known bug and will be fixed eventually.

**Comment by 0SoggyMustache0** [comment]
Bird flying has been reworked for 2.1. If your issue persists after 2.1 please create a new issue.
