### ISSUE TITLE
[Feature Request] Aggression in Cassowaries

### ISSUE THREAD

**Issue by VakyPanda** [0SoggyMustache0/ZAWA#40]
**Feature requests that do not follow this template will be ignored and closed**
**Do NOT suggest animals or model change**

**Is your feature request related to a problem? Please describe.**
Not really a problem just a suggestion. It doesn't seem right that the cassowaries being one of the most dangerous and hostile birds on the planet aren't aggressive towards the player.

**Describe the solution you'd like**
More aggressive cassowaries that attack the player if too close

**Describe alternatives you've considered**
N/A

**Additional context**
![amazing-australia](https://user-images.githubusercontent.com/63160430/78466330-a6896300-771d-11ea-8c58-3f772961a624.jpg)

**Comment by JoelZBub** [comment]
yes please

**Comment by 0SoggyMustache0** [comment]
This will be present in zawa 2.1.0
