### ISSUE TITLE
[Feature Request] Nocturnal animals should be nocturnal instead of diurnal

### ISSUE THREAD

**Issue by VakyPanda** [0SoggyMustache0/ZAWA#44]
**Feature requests that do not follow this template will be ignored and closed**
**Do NOT suggest animals or model change**

**Is your feature request related to a problem? Please describe.**
This is another suggestion related to the real life behaviour of the animals. The Tasmanian devil is observed to be mostly nocturnal in real life whereas it is diurnal in the mod. I have only observed this in the tasmanian devil and am not sure of the other creatures.

**Describe the solution you'd like**
It would be more life - like,  if the Tasmanian devils (and other creatures who are in real life nocturnal) were active during the night and slept all day. Though this is more lifelike, the devs should probably get the community's opinion because most people would probably like their nocturnal animals to be moving around in the day.
Best way to solve this would be to add a config option.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by JoelZBub** [comment]
This is a reasonable request, including the config option, IMO.
Please respond with a list of animals you feel should be included in this feature.

**Comment by VakyPanda** [comment]
*These are all the animals I think should have the nocturnal config used on:*
Japanese giant salamander
Great horned owl
Tasmanian devil
Indian pangolin
Beaver
Tree frog
Cougar ( active at dawn aswell )

**Comment by andrewminer** [comment]
There are also animals who don't have a definite sleep cycle (e.g., the echinda).

**Comment by 0SoggyMustache0** [comment]
ZAWA 2.1 will feature a JSON system for all tameable animals that will allow you to customize sleep for animals. I will not set the defaults for those animals to be nocturnal because of how sleeping works in zawa. Here is more information on the new JSON system https://github.com/0SoggyMustache0/ZAWA/blob/master/AddonCreation/AnimalPack.md
