### ISSUE TITLE
[Bug] Water mobs not spawning after 2.0.1 update

### ISSUE THREAD

**Issue by Dreytac** [0SoggyMustache0/ZAWA#47]
**Describe the bug**
In my mod pack, upon updating to ZAWA v2.0.1, no water mobs are spawning at all (except guardians). Not even Minecraft squid are spawning.

Disabling ZAWA spawning in the config and squids return. Playing around with the water despawn timer in the config doesn't make a difference.

I believe this is a mod conflict and I'm in the process (albeit slowly) of trying to figure out which ones.

**To Reproduce**
1. Create a new world with the mod pack.
2. Find river biome.

**Expected behavior**
Water mobs, including vanilla Minecraft squid should be spawning.

**Please complete the following information):**
 - Mod Version Number : 2.0.0, 2.0.1 & 2.0.2
 - Bookworm Version Number : 2.5.0 & 2.5.1
 - Forge Version Number : 14.23.5.2847
 - Is OptiFine installed? : no
 - Is this bug present in single player or on a server or both? : both
 
**Additional context**
A up-to-date list of mods in my pack can be found here: https://hobbyhome.net/crafthome/modlist

I may be able to supply a zipped instance of the mod-pack if required.

**Comment by JoelZBub** [comment]
Thanks for the detailed report and mod list. 
I've only been able to come close to duplicating this issue in existing worlds. Instantiating a new world with 2.0.2 installed has resulted in normal spawning for me. Here is a mod list that I've tested it with, possibly you can see where our lists diverge and find a conflict. 
http://bit.ly/modpackbuild
Any further info you can give from your testing with other mods would be appreciated. 
I may request a modpack export when I get time to play test it.

**Comment by JoelZBub** [comment]
Sounds to me like RNG isn't in your favor

**Comment by Dreytac** [comment]
Sounds about right but surely flying around a water only world for 10 minutes should at least give me some random generation above 0%! :)

**Comment by JoelZBub** [comment]
Any further progress on compat testing?

**Comment by Sagbvagare** [comment]
i also got this bug in an existing world
 i'm using some of the same mods such as: Bibliocraft, JEI, immersive engineering and buildcraft 
and fossils and archeology
i also noticed that not only aquatic mobs were not spawning but some of the ones already in the world disappeared (some dolphins and blue fish), but i can still spawn them with their spawners

**Comment by HavocC4** [comment]
Hey!

I also have this issue while using zawa 2.0.2.
As stated above i'm using Forge 14.23.5.2847, using bookworm 2.5.1 and this bug appears in both single and multiplayer.
I noticied that Zawa aquatic mobs and squids do not spawn, however, fossil and archeology mobs and guardians generated by quark do spawn in the oceans.
If i use spawn eggs, zawa mobs work as expected.

I've already tried to edit the config file of the mods unsuccefully.
I'm running a custom modpack in 1.12.2. If you wish so, I can provide you the config and mods folders in order for you to reproduce the bug. 
I'm attaching the mod list i'm using.
![Mods](https://user-images.githubusercontent.com/63442557/78969385-1e350480-7b07-11ea-90a6-9e71e85c164a.PNG)

**Comment by Dreytac** [comment]
@JoelZBub: Nothing yet. I have notices some other spawning quirks that I'm not sure are related to ZAWA. They include very low spawn rates and instant despawns. I'm still hunting for the cause. It's frustrating me because if I just take out ZAWA, NaturalFauna and Lil' Critters, everything goes back to normal. I'm still plugging away though.

@Sagbvagare: Do you have a list of all the mods in your pack?

@HavocC4: Thanks for the list of mods. I'll combine the multiple lists to see what is common and focus on that.

**Comment by pixzi** [comment]
> Edit2: It seems I can consistently generate a water only world (using the water world preset in Minecraft) that generates water mobs... on initial spawn. After that, nothing spawns except guardians.

> 

This is the same issue I've been having myself, i tested this with just ZAWA. Still no water spawns except for initial ones at first login.

**Comment by elieroumet** [comment]
> > Edit2: It seems I can consistently generate a water only world (using the water world preset in Minecraft) that generates water mobs... on initial spawn. After that, nothing spawns except guardians.
> 
> > 
> 
> This is the same issue I've been having myself. Still no water spawns except for initial ones at first login. - Depending on world, not even that.

After some trials, its exacly the same problem i'm having, a couple of ZAWA aquatic mobs spawn during the initial world generation but nothing spawns while new chunks are loaded

**Comment by Dreytac** [comment]
So after getting frustrated, I decided to come at this from the other end. I started a new pack with JUST ZAWA and Bookworm on Forge 14.23.5.2847. I found this isn't a mod conflict at all and is a ZAWA bug.

Steps to reproduce:
1. Create an instance with Forge 14.23.5.2847, Bookworm 2.5.1 and ZAWA 2.0.2.
2. Create a new superflat world with the "Water World" preset.
3. When you join you will notice ZAWA water mobs have spawned in. Hit F3 and fly away until the entity count reaches 0. Stay there and you will see that nothing else spawns in.

I then disabled ZAWA (not Bookworm) and re-created the world. Upon flying around, squid are constantly spawning in.

**Comment by JoelZBub** [comment]
Thank you for the thorough investigation. We'll move forward with resolving this.

**Comment by WATOTATO** [comment]
> So after getting frustrated, I decided to come at this from the other end. I started a new pack with JUST ZAWA and Bookworm. I found this isn't a mod conflict at all and is a ZAWA bug.
> 
> Steps to reproduce:
> 
> 1. Create an instance with Forge 14.23.5.2847, Bookworm 2.5.1 and ZAWA 2.0.2.
> 2. Create a new superflat world with the "Water World" preset.
> 3. When you join you will notice ZAWA water mobs have spawned in. Hit F3 and fly away until the entity count reaches 0. Stay there and you will see that nothing else spawns in.
> 
> I then disabled ZAWA (not Bookworm) and re-created the world. Upon flying around, squid are constantly spawning in.
> 
> So it seems the initial spawn works and then ZAWA decides not to spawn any more (an internal mob counter perhaps?). This also explains why it "appears" to work on new worlds but not old ones.
> 
> **Edit:** This is also an issue with mob spawns in general! It's not limited to water mobs. Create a new superflat grass world, fly away from the spawn area and you'll notice that NO new mobs (not even vanilla mobs) will spawn! Remove ZAWA, recreate world, fly away from spawn and vanilla mobs should spawn in.
> 
> **Edit2:** I think ZAWA fills the mob cap for passive animals in the spawn chunks which then prevents more mobs from spawning. This can be tested by sitting at spawn until the cap fills then flying away. You'll notice no more mobs spawn. Use the command "/kill @e[type=!player]" to then kill all entities and you'll notice mobs spawn back in. Fly away and after a short period of time, mobs will spawn.
> 
> I think that also explains why water mobs don't respawn because once they despawn the cap is then filled with land mobs. Do land based mobs have a despawn timer as well anymore?

Heeeeelp, how do I make ZAWA work on my single player world? I dont want to mess up. 
Thanks

**Comment by WATOTATO** [comment]
> So after getting frustrated, I decided to come at this from the other end. I started a new pack with JUST ZAWA and Bookworm. I found this isn't a mod conflict at all and is a ZAWA bug.
> 
> Steps to reproduce:
> 
> 1. Create an instance with Forge 14.23.5.2847, Bookworm 2.5.1 and ZAWA 2.0.2.
> 2. Create a new superflat world with the "Water World" preset.
> 3. When you join you will notice ZAWA water mobs have spawned in. Hit F3 and fly away until the entity count reaches 0. Stay there and you will see that nothing else spawns in.
> 
> I then disabled ZAWA (not Bookworm) and re-created the world. Upon flying around, squid are constantly spawning in.
> 
> So it seems the initial spawn works and then ZAWA decides not to spawn any more (an internal mob counter perhaps?). This also explains why it "appears" to work on new worlds but not old ones.
> 
> **Edit:** This is also an issue with mob spawns in general! It's not limited to water mobs. Create a new superflat grass world, fly away from the spawn area and you'll notice that NO new mobs (not even vanilla mobs) will spawn! Remove ZAWA, recreate world, fly away from spawn and vanilla mobs should spawn in.
> 
> **Edit2:** I think ZAWA fills the mob cap for passive animals in the spawn chunks which then prevents more mobs from spawning. This can be tested by sitting at spawn until the cap fills then flying away. You'll notice no more mobs spawn. Use the command "/kill @e[type=!player]" to then kill all entities and you'll notice mobs spawn back in. Fly away and after a short period of time, mobs will spawn.
> 
> I think that also explains why water mobs don't respawn because once they despawn the cap is then filled with land mobs. Do land based mobs have a despawn timer as well anymore?

How did you disable ZAWA I just press the button and nothing happens. If you could help me I would be really pleased thank u

**Comment by WATOTATO** [comment]
> So after getting frustrated, I decided to come at this from the other end. I started a new pack with JUST ZAWA and Bookworm. I found this isn't a mod conflict at all and is a ZAWA bug.
> 
> Steps to reproduce:
> 
> 1. Create an instance with Forge 14.23.5.2847, Bookworm 2.5.1 and ZAWA 2.0.2.
> 2. Create a new superflat world with the "Water World" preset.
> 3. When you join you will notice ZAWA water mobs have spawned in. Hit F3 and fly away until the entity count reaches 0. Stay there and you will see that nothing else spawns in.
> 
> I then disabled ZAWA (not Bookworm) and re-created the world. Upon flying around, squid are constantly spawning in.
> 
> So it seems the initial spawn works and then ZAWA decides not to spawn any more (an internal mob counter perhaps?). This also explains why it "appears" to work on new worlds but not old ones.
> 
> **Edit:** This is also an issue with mob spawns in general! It's not limited to water mobs. Create a new superflat grass world, fly away from the spawn area and you'll notice that NO new mobs (not even vanilla mobs) will spawn! Remove ZAWA, recreate world, fly away from spawn and vanilla mobs should spawn in.
> 
> **Edit2:** I think ZAWA fills the mob cap for passive animals in the spawn chunks which then prevents more mobs from spawning. This can be tested by sitting at spawn until the cap fills then flying away. You'll notice no more mobs spawn. Use the command "/kill @e[type=!player]" to then kill all entities and you'll notice mobs spawn back in. Fly away and after a short period of time, mobs will spawn.
> 
> I think that also explains why water mobs don't respawn because once they despawn the cap is then filled with land mobs. Do land based mobs have a despawn timer as well anymore?

How do I disable mods? thanks I have the same problem

**Comment by Taylor-666** [comment]
I have the latest version of the zawa mod and no water mods will spawn how can i fix it.

**Comment by 0SoggyMustache0** [comment]
Too many people are somehow unable to comprehend that this issue is still being worked on and that this report is NOT for reporting other things or asking questions. I am locking this until further information is needed from the original poster.

**Comment by JoelZBub** [comment]
The hypotheses about this being related to zawa passive mobs filling the mob cap is incorrect. I've tested this with ZAWA land spawn rates turned way down (weights from 2 to 5 on all entities).
![2020-06-14_15 01 00](https://user-images.githubusercontent.com/12024500/84601653-e83a3680-ae4f-11ea-82a2-3966d363d3d3.png)
As you can see from this screenshot there are very few **total** entities in world and only a few ZAWA water mobs  as well.

**Comment by JoelZBub** [comment]
![2020-07-09_08 30 29](https://user-images.githubusercontent.com/12024500/87040395-9ec6d800-c1be-11ea-840a-44a160d87b99.png)
Still not entirely convinced this is actually an issue

**Comment by JoelZBub** [comment]
![2020-07-09_08 33 20](https://user-images.githubusercontent.com/12024500/87040546-df265600-c1be-11ea-93c5-b991745ffa04.png)

**Comment by 0SoggyMustache0** [comment]
We are unable to duplicate this issue. Try another world or change the spawn configs.
