### ISSUE TITLE
[Bug] Pyropia is causing a visual glitch with shaders.

### ISSUE THREAD

**Issue by TheTennessee** [0SoggyMustache0/ZAWA#49]
**Describe the bug**
While all other coral and other items added by the mod work fine, Pyropia specifically causes a visual glitch with shaders installed. I am using Optifine HD and Chocapic v8 Ultra as the shader. I don't know if it happens on other shaders, but it seems odd for only one item to do it. I am attaching some pictures to show what I mean.

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. Install Optifine HD
2. Install a shader (Mine was Chocapic v8 Ultra)
3. Look down into the water at the black marks visible from the surface
4. Get down next to the pyropia to see the water through the model

**Expected behavior**
Pyropia should render like all other coral and underwater items added by the mod.

**Screenshots**
![2020-04-10_17 37 56](https://user-images.githubusercontent.com/5052078/79025662-6e868380-7b54-11ea-90ff-86e582132416.png)
![2020-04-10_17 38 14](https://user-images.githubusercontent.com/5052078/79025853-f40a3380-7b54-11ea-95c3-84368bdd8461.png)

**Please complete the following information):**
 - Mod Version Number : 2.0.2 for 1.12.2
 - Bookworm Version Number : 2.5.1 for 1.12.2
 - Forge Version Number : 8.0.99.99
 - Is OptiFine installed? : Yes
 - Is this bug present in single player or on a server or both? : both

**Comment by TheTennessee** [comment]
Update: It's definitely not the texture. I messed with the .jar file, replaced the pyropia texture with one for the coralberry, and it still has the same issue. It has to do with the way it is rendering (seemingly excluded from alpha sorting and lighting). The screenshot attached shows the texture at full brightness during the night too.
![2020-04-10_18 25 07](https://user-images.githubusercontent.com/5052078/79028946-3b49f180-7b60-11ea-9631-6aaa8194d844.png)

**Comment by 0SoggyMustache0** [comment]
I cannot duplicate this with the shader I have on so this is an issue with the shader you are using. You'll have to report it to whoever made the shader, I haven't done any special rendering tricks that could result in this.
