### ISSUE TITLE
[Bug] No Underwater Plants Spawn.

### ISSUE THREAD

**Issue by josephgilbert** [0SoggyMustache0/ZAWA#5]
**Issues that dont follow this template will be ignored and closed**

**Test before making a report by removing all mods except ZAWA, Bookworm and ZAWA Add-ons. Check that you are using the latest versions of these mods**

**Describe the bug**
I'm not sure if this is even a bug, but I feel like it is.  After installing the latest version of the mod, I found that no underwater plants were spawning in oceans and other biomes that they should.  I checked the configuration files, and it says that coral and kelp should be generating naturally.  

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1.
2.
3.
4.
More steps...

**Expected behavior**
Plants introduced by the mod should spawn underwater.

**Screenshots**
![Bug](https://user-images.githubusercontent.com/42681167/77259147-ecdabe80-6c55-11ea-9056-cdc7fdd62cbd.png)

** Crash Report or Game Log**
If your game crashed, paste your crash report to https://pastebin.com/ or similar service and paste the link in place of this sentence.

**Please complete the following information):**
 - Mod Version Number :  2.0.0
 - Bookworm Version Number :  2.5.0
 - Forge Version Number :  14.23.5.2836
 - Is OptiFine installed? :  Yes.

**Additional context**
I am using a resource pack that replaces the textures for the seagrass and kelp.  None of the textures for any of the other underwater plants are replaced though.

**Comment by 0SoggyMustache0** [comment]
Thank you for the report. I've reproduced it and will fix it.

**Comment by 0SoggyMustache0** [comment]
This is fixed and the patch will be available when ZAWA 2.0.1 releases.

**Comment by josephgilbert** [comment]
Amazing!  Thank you for the quick response!
