### ISSUE TITLE
Poachers spawn everywhere on superflat maps

### ISSUE THREAD

**Issue by Ebirah766** [0SoggyMustache0/ZAWA#50]
I've no clue why this is happening, but I feel like it needs to be submitted.

**Comment by Ebirah766** [comment]
> I've no clue why this is happening, but I feel like it needs to be submitted.

If you need extra info you can ask.

**Comment by JoelZBub** [comment]
Please use the config to disable them

**Comment by 0SoggyMustache0** [comment]
Cannot duplicate. Use the configs.
