### ISSUE TITLE
[Bug] i have this proble with this mod, 

### ISSUE THREAD

**Issue by Alee-OneHit** [0SoggyMustache0/ZAWA#51]
Hello, I have a problem with this mod, I have completely removed it from my server, but it is still throwing an error in the console, due to the entities that supposedly remain, even if I have confirmed the FML, it is very annoying for me to read the console My server, why does this error that I will send below come up all the time, I just hope you help me:

13.04 23:04:13 [Server] WARN Skipping BlockEntity with id snowrealmagic:snow
13.04 23:04:13 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:13 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:13 [Server] WARN Skipping BlockEntity with id treasure2:proximity_spawner_tile_entity
13.04 23:04:13 [Server] WARN Skipping BlockEntity with id treasure2:proximity_spawner_tile_entity
13.04 23:04:13 [Server] WARN Skipping BlockEntity with id treasure2:wood_chest_tile_entity
13.04 23:04:13 [Server] WARN Skipping BlockEntity with id treasure2:proximity_spawner_tile_entity
13.04 23:04:16 [Server] WARN Skipping Entity with id zawa:westernlowlandgorilla
13.04 23:04:16 [Server] WARN Skipping Entity with id zawa:westernlowlandgorilla
13.04 23:04:16 [Server] WARN Skipping Entity with id zawa:westernlowlandgorilla
13.04 23:04:16 [Server] WARN Skipping Entity with id zawa:redkangaroo
13.04 23:04:16 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:16 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:16 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:16 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:16 [Server] WARN Skipping Entity with id zawa:westernlowlandgorilla
13.04 23:04:16 [Server] WARN Skipping Entity with id zawa:westernlowlandgorilla
13.04 23:04:16 [Server] WARN Skipping Entity with id zawa:redkangaroo
13.04 23:04:16 [Server] WARN Skipping Entity with id zawa:blackspidermonkey
13.04 23:04:16 [Server] WARN Skipping Entity with id zawa:bengaltiger
13.04 23:04:16 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:21 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:21 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:21 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:21 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:21 [Server] WARN Skipping BlockEntity with id treasure2:proximity_spawner_tile_entity
13.04 23:04:21 [Server] WARN Skipping BlockEntity with id treasure2:proximity_spawner_tile_entity
13.04 23:04:21 [Server] WARN Skipping BlockEntity with id treasure2:proximity_spawner_tile_entity
13.04 23:04:21 [Server] WARN Skipping BlockEntity with id treasure2:crate_chest_tile_entity
13.04 23:04:21 [Server] WARN Skipping BlockEntity with id treasure2:proximity_spawner_tile_entity
13.04 23:04:21 [Server] WARN Skipping BlockEntity with id treasure2:proximity_spawner_tile_entity
13.04 23:04:21 [Server] WARN Skipping BlockEntity with id treasure2:proximity_spawner_tile_entity
13.04 23:04:21 [Server] WARN Skipping BlockEntity with id treasure2:proximity_spawner_tile_entity
13.04 23:04:22 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:24 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:24 [Server] WARN Skipping Entity with id zawa:redkangaroo
13.04 23:04:25 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:25 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:25 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:26 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:27 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:27 [Server] WARN Skipping Entity with id zawa:redkangaroo
13.04 23:04:27 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:27 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:27 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:27 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:27 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:27 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:27 [Server] WARN Skipping Entity with id zawa:indianpangolin
13.04 23:04:28 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:28 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:29 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:29 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:29 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:29 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:29 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:29 [Server] WARN Skipping Entity with id zawa:macaw
13.04 23:04:29 [Server] WARN Skipping BlockEntity with id treasure2:crate_chest_moldy_tile_entity
13.04 23:04:29 [Server] WARN Skipping Entity with id zawa:redkangaroo

**Comment by 0SoggyMustache0** [comment]
This is something you'd have to report to forge I guess. Once you remove the mod theres nothing the mod can do about it to cause the console spam.

**Comment by JoelZBub** [comment]
This happens with literally every mod you remove.
