### ISSUE TITLE
[Bug] Too many poachers spawn in a flat world

### ISSUE THREAD

**Issue by FadiMasannat** [0SoggyMustache0/ZAWA#52]
**Issues that dont follow this template will be ignored and closed**

**Test before making a report by removing all mods except ZAWA, Bookworm and ZAWA Add-ons. Check that you are using the latest versions of these mods. Delete these lines when making a report.**

**Describe the bug**
Too many poachers are spawning in my flat zoo world, and it makes the game so laggy and the FPS drops to 0 every now and then.
**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. I was in my overworld flat world, and after I updated the mod to the latest version, countless poachers were spawning.
2. There were poachers spawning in groups of 5 every 8 blocks and they won't despawn.
3. The poachers cannot be stopped !
4.
More steps...

**Expected behavior**
I expected that the poachers will stop spawning, but that never happened.
**Screenshots**

** Crash Report or Game Log**
If your game crashed, paste your crash report to https://pastebin.com/ or similar service and paste the link in place of this sentence.

**Please complete the following information):**
 - Mod Version Number :1.12.2-2.0.2
 - Bookworm Version Number :1.12.2-2.5.1
 - Forge Version Number :14.23.5.2847
 - Is OptiFine installed? : Yes
 - Is this bug present in single player or on a server or both? : Single player
 
**Additional context**
Add any other context about the problem in place of this sentence.

**Comment by JoelZBub** [comment]
Did you bother to turn them off in the config?

If you turned them off, do </kill @e[type=zawa:poacher]> to remove them from your world.
If they continue spawning, let us know, otherwise I'm closing this issue.

**Comment by PleaseInsertCreativeName** [comment]
I actually have the same issue with my survival world. The poachers spawn everywhere. 

And i just tried to use the kill command but well... they died but immediatly afterwards they started spawning again. And I have them turned off in the config. That´s really anoying, because I just started using this mod and it looks really amazing but most mobs that spawn are the poachers so...

**Comment by JoelZBub** [comment]
Give me a mod list.
I'm going to go out on a limb here and guess that you are using Mo Creatures' spawn utility Custom Mob Spawner.

**Comment by PleaseInsertCreativeName** [comment]
Removing Mo Creatures and the Custom Mob Spawner worked for me.

**Comment by JoelZBub** [comment]
Thanks for the reply.

**Comment by BetterToBeBloody** [comment]
Hi, I have the same problem, and I was wondering if after you removed mo creatures as well as the custom mob spawners, if once you fixed the problem, you could redownload the mods and the problem would be fixed still? Cause I love playing with Mo Creatures and would like to play with both.

Thank you!
