### ISSUE TITLE
[Bug]Andean Condor sits on shoulder with its wings open

### ISSUE THREAD

**Issue by VakyPanda** [0SoggyMustache0/ZAWA#58]
**Issues that dont follow this template will be ignored and closed**

**Describe the bug**
The Andean Condor never closes its wings whenever sitting on the players shoulder
Suspected Mod : ZAWA Rebuilt

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1.Spawn Andean Condor
2.Tame With Raptor kibble
3.Right click to shoulder it
4.Wings are always open
More steps...

**Expected behavior**
Wings should close like when the Harpy Eagle is sitting on your shoulder
**Screenshots**

![2020-04-19_04 41 36](https://user-images.githubusercontent.com/63160430/79673659-38eb3580-81f9-11ea-9402-e77807f6ed3a.png)
![2020-04-19_04 41 47](https://user-images.githubusercontent.com/63160430/79673667-43a5ca80-81f9-11ea-9100-3eda8c723634.png)

** Crash Report or Game Log**
No Crash

**Please complete the following information):**
 - Mod Version Number : zawa-1.12.2-2.0.2.jar
 - Bookworm Version Number : bookworm-1.12.2-2.5.1.jar
 - Forge Version Number : forge-14.23.5.2847
 - Are other mods installed? : Yes
 - Is OptiFine installed? : Yes
 - Is this bug present in single player or on a server or both? :
 
**Additional context**
Add any other context about the problem in place of this sentence.

**Comment by 0SoggyMustache0** [comment]
Thank you for the report. This will be fixed for 2.1.
