### ISSUE TITLE
[Bug] Cassowary Description Bug

### ISSUE THREAD

**Issue by MLGMagicHoodini** [0SoggyMustache0/ZAWA#6]
**Describe the bug**
When using the Data Book on the cassowary and going to the description there will be some errors and symbols that should't be there

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1.Spawn cassowary
2.Get a Data book
3.Use Data Book on Cassowary
4.Go to Description

**Expected behavior**
After checking the game files i saw that there wasn't any symbols like in game this could be caused by the use of ' and others symbols that minecraft doesn't recognize

**Screenshots**
![image](https://user-images.githubusercontent.com/52632295/77259154-7e0e5d00-6c77-11ea-8609-5bb8c99eba7e.png)

**Please complete the following information):**
 - Mod Version Number : 2.0.0
 - Bookworm Version Number : 2.5.0
 - Forge Version Number : 2846
 - Is OptiFine installed? : Yes

**Comment by JoelZBub** [comment]
![2020-03-22_17 53 20](https://user-images.githubusercontent.com/12024500/77261624-33381980-6c66-11ea-97e6-6fc5560ebee5.png)
Can duplicate

**Comment by 0SoggyMustache0** [comment]
Issue identitifed and will be fixed for 2.0.1
