### ISSUE TITLE
[BUG] Saddled animals lose the capacity to move

### ISSUE THREAD

**Issue by Wolfixsp** [0SoggyMustache0/ZAWA#62]
**When i saddle a tamed creature and mount it it work just fine for a minute then it just stops moving.**
- This also happens after dismounting said creature.
- Leashes or using a net doesn't fix it.
- Only fix i could find it's relogin which doesn't really help.

**Comment by 0SoggyMustache0** [comment]
I am able to duplciate this and it should be fixed for 2.1 I will update when it is.

**Comment by JoelZBub** [comment]
Roll back your mod version to 2.0.2

**Comment by 0SoggyMustache0** [comment]
This has been fixed for zawa 2.0.32
