### ISSUE TITLE
[Bug] Tamed Animals don´t move 

### ISSUE THREAD

**Issue by TronikTheBug** [0SoggyMustache0/ZAWA#63]
So I updated the latest version of ZAWA today and since then all my tamed animals don´t move. Their animaton still works (they blink with their eyes and stuff) but they´re freezing. That´s so far a problem, that they don´t reach their food and normaly decreasing their hunger. The other mobs (vanilla and untamed ZAWAs) still walk and move. 

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. Played ZAWA 2.0.2, then learned that there is an update out.
2. Update via Twitch
3. Reload game
4. Bug: tamed animals don´t move

I turned off the the other mods, except for Zawa and Bookworm, but the issue still exist. 

 - Mod Version Number :1.12.2-2.0.3
 - Bookworm Version Number : 1.12.2-2.5.1
 - Forge Version Number :
 - Are other mods installed? : ZAWA Addons, Dynamic Trees, Biomes O´Plenty, JourneyMap, JEI, Traveller´s Backpack
 - Is OptiFine installed? : no
 - Is this bug present in single player or on a server or both? : only play single player 
 

Thank you for your help,
Tronik

**Comment by JoelZBub** [comment]
Is this in an existing world? does this happen in a new world?

**Comment by TronikTheBug** [comment]
I created a new world. The tamed animals there move normaly. So I went to my old world and tamed some wild animals and they´re moving too. Just my old ones are freezing still :/

**Comment by JoelZBub** [comment]
You'll have to roll back to the previous version then, or place new animals until a fix is realized.
(Keep in mind that updates on any mod can break previous worlds and this may not receive a fix that preserves your world made in a prior version.)

**Comment by TronikTheBug** [comment]
Yes, I guess, I´ll kill and replace all the old animals. In the end I´m happy you guys do updates and progress :) Thank you

**Comment by 0SoggyMustache0** [comment]
This has been fixed for zawa 2.0.32, please update.
