### ISSUE TITLE
[Bug] Animals don't drink by themselves and die

### ISSUE THREAD

**Issue by di0nyysus** [0SoggyMustache0/ZAWA#67]
Hi, I'm creating a zoo with friends and the tamed animals won't drink and die (if we don't tame them they disappear).

1. They won't drink from a water source close to them
2. They won't drink from water bottle or bucket we put in a barrel

The only way we can make them drink is from handing them water bottle but it's so much time consuming we'll never be able to keep them all alive
They don't appear to be playing with object either
No problem with food

 - Mod Version Number: zawa-1.12.2-2.0.3
 - Bookworm Version Number: bookworm-1.12.2-2.5.0
 - Forge Version Number: forge-1.12.2-14.23.5.2846-universal
 - Are other mods installed? : not yet but we plan on putting a mod to take pictures
 - Is OptiFine installed? : no
 - Is this bug present in single player or on a server or both? : server, didn't try in singleplayer

Thank for helping me
 
edit : we're in creative mode

**Comment by 0SoggyMustache0** [comment]
I can't duplicate this. Use 2.0.2 of zawa and 2.5.1 of bookworm. 2.0.3 is a beta so there are bound to be issues with it. If 2.0.2 still causes issues then go back to 2.0.1.
