### ISSUE TITLE
[Bug] Beavers can't get out of the water.

### ISSUE THREAD

**Issue by Shatter0Ice** [0SoggyMustache0/ZAWA#68]
**Describe the bug**

 Beavers can't get out of the water, I noticed in survival since the animal was losing happiness, then to make such it wasnt the lilypads I tried this on creative, even with only 2 blocks of water, and two beavers, they couldnt get out of the water, only the baby seems to be able to since when I pushed him he got out pretty easily.

**To Reproduce**

1. have a beaver
2. have water
3. put the beaver in the water

**Expected behavior**

 Being able to get out of the water

**Please complete the following information):**

 - Mod Version Number : 2.0.2
 - Bookworm Version Number : 2.5.1
 - Forge Version Number : 2838
 - Are other mods installed? : Yes
 - Is OptiFine installed? : Yes
 - Is this bug present in single player or on a server or both? : Only tried in singleplayer

**Comment by 0SoggyMustache0** [comment]
Closing this to leave to one thread.
