### ISSUE TITLE
[Bug] Missing Descriptions

### ISSUE THREAD

**Issue by MLGMagicHoodini** [0SoggyMustache0/ZAWA#7]
**Describe the bug**
Some animals like Rattlesnake won't have any description

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. Spawn Rattlesnake
2. Get a Data Book
3. Use Data Book on Rattlesnake

**Expected behavior**
Like all animals there should be 3 pages and 3rd page would be the description and for rattlesnake this doesn't happen

**Screenshots**
![image](https://user-images.githubusercontent.com/52632295/77259214-e8270200-6c77-11ea-9a8a-a49e7afc3b3c.png)

**Please complete the following information):**
 - Mod Version Number : 2.0.0
 - Bookworm Version Number : 2.5.0
 - Forge Version Number : 2846
 - Is OptiFine installed? : Yes

**Comment by 0SoggyMustache0** [comment]
Fixed for 2.0.1
