### ISSUE TITLE
Tamed coconut crabs causing lag

### ISSUE THREAD

**Issue by Audhumbla** [0SoggyMustache0/ZAWA#72]
I tamed a coconut crab told it to stay with the book and not only did it not stop moving. I went over to it to try and put it back on stay but as soon as I got close it started lagging me. It seems to only be the tame coconut crabs not the wild ones.

**Comment by 0SoggyMustache0** [comment]
This does not follow any of the formatting. Please make a new issue where you actually leave the template and fill it out properly.
