### ISSUE TITLE
[Feature Request] More translation keys

### ISSUE THREAD

**Issue by 0SoggyMustache0** [0SoggyMustache0/ZAWA#73]
**Feature requests that do not follow this template will be ignored and closed**
**Do NOT suggest animals or model change**

**Is your feature request related to a problem? Please describe.**
None of the GUIs use the lang file for translations which makes the game hard to play if you don't speak English.

**Describe the solution you'd like**
Add translation keys for all GUIs, messages, and text that ZAWA uses

**Describe alternatives you've considered**
Learning English.

**Comment by 0SoggyMustache0** [comment]
2.1 Will include lots of new keys for the data book and animal tracker. Below are the english keys if anyone reading this wants a head start.
`zawa.gui.zookeeper=Zoo Keeper
zawa.gui.tamed_on=Tamed on
zawa.gui.male=Male
zawa.gui.female=Female
zawa.gui.sex=Sex
zawa.gui.variant=Variant
zawa.gui.trait=Trait
zawa.gui.tamed_with=Tamed with
zawa.gui.bred_with=Bred with
zawa.gui.diet=Diet
zawa.gui.enrichment=Enrichment
zawa.gui.science=Scientific Name
zawa.gui.conservation=Conservation Status
zawa.gui.region=Region
zawa.gui.page=Page
zawa.gui.dead=Is Dead.
zawa.gui.name=Name
zawa.gui.pos=Position
zawa.gui.health=Health
zawa.gui.child=Child`

**Comment by TobiPeterG** [comment]
> 2.1 Will include lots of new keys for the data book and animal tracker. Below are the english keys if anyone reading this wants a head start.
> `zawa.gui.zookeeper=Zoo Keeper zawa.gui.tamed_on=Tamed on zawa.gui.male=Male zawa.gui.female=Female zawa.gui.sex=Sex zawa.gui.variant=Variant zawa.gui.trait=Trait zawa.gui.tamed_with=Tamed with zawa.gui.bred_with=Bred with zawa.gui.diet=Diet zawa.gui.enrichment=Enrichment zawa.gui.science=Scientific Name zawa.gui.conservation=Conservation Status zawa.gui.region=Region zawa.gui.page=Page zawa.gui.dead=Is Dead. zawa.gui.name=Name zawa.gui.pos=Position zawa.gui.health=Health zawa.gui.child=Child`

Hey there,

I've completely revamped the German translation file to make the translations actually make sense sometimes and to add missing strings.
The file can be found [here](https://drive.google.com/file/d/1KU8VcnDyckMRZeLn2AWY5qW6F-qXyAR6/view?usp=sharing), I've already included the new keys. :)
Btw. AFAIK you can remove the "ger_de.lang" file, since the German language files are always calles "de_de.lang". But I don't know, maybe it serves a purpose, I just noticed it. ;)

Have a nice day!

**Comment by 0SoggyMustache0** [comment]
Thank you very much. I will add your file for 2.1
