### ISSUE TITLE
[Feature Request] poachers 

### ISSUE THREAD

**Issue by flowerbabe63** [0SoggyMustache0/ZAWA#77]
I'm always frustrated when poachers spawn they are a good feature however too many of them spawn, so maybe if their spawn rate was less it would be better.

**Comment by 0SoggyMustache0** [comment]
Play the mod before you request things that have been in it forever.

**Comment by flowerbabe63** [comment]
No need to be rude, was simply just a thought. I'm still very impressed by
the mod overall as a whole.
