### ISSUE TITLE
crashes on startup

### ISSUE THREAD

**Issue by anonymus411** [0SoggyMustache0/ZAWA#78]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Zoo and Wild Animals Mod: Rebuilt (zawa)

**Comment by anonymus411** [comment]
says caused by bookworm

**Comment by 0SoggyMustache0** [comment]
Update it.

**Comment by anonymus411** [comment]
which one do you mean by update??
