### ISSUE TITLE
[Feature Request] Male/Female spawning ratio options

### ISSUE THREAD

**Issue by 0SoggyMustache0** [0SoggyMustache0/ZAWA#79]
**Feature requests that do not follow this template will be ignored and closed**
**Do NOT suggest animals or model change**

**Is your feature request related to a problem? Please describe.**
Replace this sentence with a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
Animal JSON data should allow for males/females to have different spawn chances.

**Comment by JoelZBub** [comment]
And albinos/melanistics, too.

**Comment by 0SoggyMustache0** [comment]
These will be available on JSON in 2.1 with the tag 'male_gender_percent' (float), 'rare_variants' (int arry) and 'breed_variants' (int array)
