### ISSUE TITLE
[Meta] More prominently display the patreon page on curseforge and other download sites.

### ISSUE THREAD

**Issue by WaldoTheRanger** [0SoggyMustache0/ZAWA#82]
This is an awesome mod, and has gotten a lot of attention. however, it seems that funding for further development and updates is severely lacking despite the popularity.
I and many others would love to see this mod updated and further improved, but it's very hard to find the patreon page, which would allow this to happen.

I think this can easily be solved by promoting the patreon page in all places where the mod can be downloaded, making it clear that the support milestone has to be reached before an update is possible.

I'm not sure there are alternatives to this issue, though other forms of promotion may be possible.

**Comment by 0SoggyMustache0** [comment]
I agree. I will see where I can put links on our pages so they get more attention and update this as I do that.

**Comment by 0SoggyMustache0** [comment]
It isnt much but I have added links to the zawa patreon and my personal patreon onto our cursepage. https://www.curseforge.com/minecraft/mc-mods/zoo-wild-animals-rebuild I'll close this for now but will see other comments left here if there are any suggestions.
