### ISSUE TITLE
ocean plants near surface drop on chunk generation

### ISSUE THREAD

**Issue by kr8vzn** [0SoggyMustache0/ZAWA#84]
Using MC 1.12.2, ZAWA 2.0.35

Ocean corals and other plants drop on generation, possibly because they are generated too close to the surface.
If I try to place them where they drop they can't be placed. They must be placed at least 3 blocks beneath surface. It looks like they may be generating 2 blocks below surface and dropping.

(I am using realdrops mod so they float on the surface and are easily visible)

**Comment by V-Boy** [comment]
I've had this issue as well

**Comment by 0SoggyMustache0** [comment]
This is fixed for zawa 2.1
