### ISSUE TITLE
Zawa crash

### ISSUE THREAD

**Issue by iiHector3433** [0SoggyMustache0/ZAWA#86]
Im using TLauncher

Why i say Zawa crash but so many mods?
I already tried it with zawa and bookworm and then it crashed!

So when i played the first 2 minutes in th game it looks normal
But after that the game crash
It says
Minecraft did not start due to an unknown error! Probably it happened for your mods, try to delete it or read below  You have installed mods. We advise you to assemble your assembly using our mod-pack system link . 

 - Minecraft version: 1.12.2
 - Bookworm Version Number : 1.12.2-2.5.1
 - Forge Version Number : Idk but i played version: Forge 1.12.2
 - Are other mods installed? : Yes
 - Is OptiFine installed? :  No
 - Is this bug present in single player or on a server or both? : Only single cuz i play myself
 - Minecraft Ram limit: 1300MB

Mod installed : 
- bookworm-1.12.2-2.5.1
- tlskincape_1.12.2-1.4
- zawa-1.12.2-2.0.35
- BiomeStaff-1.12.2-1.0.0
- Far_From_Home-trial-1.12.2-4.0.1
- jei_1.12.2-4.15.0.291
- lilcritters-1.12.2-1.0.0.1
- llibrary-1.7.19-1.12.2
- Mo-Creatures-Mod-1.12.2
- NaturalFauna+Mod-1.12.2-1.5.1
- OpenTerrainGenerator-1.12.2+-+v8.3
- tropicraft-MC1.12.2-7.1.9.115
- worldedit-forge-mc1.12.2-6.1.10-dist

CPU: Intel core 2 duo e7600 (kinda suck :/)
VGA; no :/
Ram: 2gb
Windows 7 ultimate

Pls tell me how to fix this pls!

**Comment by 0SoggyMustache0** [comment]
Follow the template better.
