### ISSUE TITLE
[Bug] According to Performant, some ZAWA mobs are adding too much AI tasks

### ISSUE THREAD

**Issue by V-Boy** [0SoggyMustache0/ZAWA#88]
**Describe the bug**
According to Performant, ZAWA mobs like Frigate are adding too much AI tasks with could slow down a server
**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. load up a world with performant and ZAWA
2. Pay attention to the log by performant detailing AI errors from ZAWA

**Expected behavior**
No server lag and no log errors from performant

**Screenshots**
![image](https://user-images.githubusercontent.com/40730042/83342744-a38f9680-a2b8-11ea-83fd-a3212c68d1fd.png)

** Crash Report or Game Log**
https://hastebin.com/uvelizuhaz.rb

**Please complete the following information):**
 - Mod Version Number : zawa-1.12.2-2.0.35.jar
 - Bookworm Version Number : bookworm-1.12.2-2.5.1.jar
 - Forge Version Number :  forge-14.23.5.2854
 - Are other mods installed? : Just ZAWA, bookworm, and performant, lag goggles and its library (still happens without lag goggles)
 - Is OptiFine installed? : No
 - Is this bug present in single player or on a server or both? : Both
 
https://github.com/ldtteam/Performant/issues/32
this issue could possibly help, it details another incident with another mob that performant detected had issues with one of its mobs.

**Comment by JoelZBub** [comment]
You're gonna have to explain what Performant is.

**Comment by JoelZBub** [comment]
Are you actually experiencing server performance issues or are you reporting this because It _could cause_ issues?

**Comment by V-Boy** [comment]
Performant’s curseforge page: This is a small,lightweight mod project which hugely improves TPS and blocklag.
It also logs mobs that are adding too many ai tasks which could lead to bad TPS.

Yes, I’m reporting it because according to the mod author it could lead to major trashing of TPS. I’ve had dips in my server TPS occasionally.

**Comment by 0SoggyMustache0** [comment]
I've changed some of how AI is handled for the next update, when it is available please update to it and any AI issues you may have had will be better.
