### ISSUE TITLE
[Bug] A thing does some other thing when a thing is doing something.

### ISSUE THREAD

**Issue by WaffleWest** [0SoggyMustache0/ZAWA#89]
**Issues that dont follow this template will be ignored and closed**

**Describe the bug**
With this modpack I have started building a zoo and adding animals. The issue is (I think it's an issue) is that the animals don't ever lose hunger, hydration, or happiness in their health bars. I do also have it in normal mode if that makes any difference rather than peaceful mode. They're constantly in a perfect state and I just want them to eat and play,etc.

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. There is no thing leading up to the issue with steps, but every once and a while I will check the animals health with the animal data book and they wouldn't have lost any hunger, etc. 

More steps...

**Expected behavior**
I expected the animals to have to eat and drink their water and to play with their enrichment.

** Crash Report or Game Log**
No crash.

**Please complete the following information):**
 - Mod Version Number : 2.0.35
 - Bookworm Version Number : 2.5.1
 - Forge Version Number : 14.23.5.2854
 - Are other mods installed? : Yes. Pam's Harvestcraft, Biomes O' Plenty, Traveller's Backpack, JEI, Dynamic trees, and some ZAWA addons (Lil' Critters and Natural Fauna Mod)
 - Is OptiFine installed? : Yes.
 - Is this bug present in single player or on a server or both? : Only single player that I know of.
 
**Additional context**

**Comment by 0SoggyMustache0** [comment]
Not a bug. Look at the config and latest changelog
