### ISSUE TITLE
Poacher spawning is messed up

### ISSUE THREAD

**Issue by Avocado-Boi** [0SoggyMustache0/ZAWA#90]
I recently opened a new world and built a cow farm with a coop, later a bunch of poachers keep mass spawning around, in, and on top of the farm/coop. I killed a bunch, moved some cows to another area in the farm, and then a bunch more spawned. I'm wondering if I can possibly get an id for the poacher so I can do a /kill every time they spawn near, or could this be fixed?

**Comment by JoelZBub** [comment]
Duplicate of #77 #52 #50 #46 #29 and #81

**Comment by Avocado-Boi** [comment]
oof.. sorry I didn't see the others... I only looked through the open issues
