### ISSUE TITLE
Zawa mobs not spawning

### ISSUE THREAD

**Issue by GoodStuffIsBadStuff** [0SoggyMustache0/ZAWA#91]
**Describe the bug**
Alright, Im pretty sure the problem is due biomes o plenty mod, but hear me out. So basically I watched a youtuber who made a modpack consist of zawa mod and biomes o plenty mod, and I tried the the modpack itself and it worked, the creatures do spawn in a non vanilla biomes. A few dayss past(I think), got a new laptop, try to play minecraft with mods and then use the biomes o plenty preset, and then non of the creatures from zawa spawn, they only spawn in vanilla biomes cause I saw them spawning on beaches and oceans while in the same world. And I tried creating new worlds, one without biomes o plenty preset and one with, the 'without' ofc have the zawa mobs spawning but the 'with' doesnt.

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1.use biomes o plenty preset when creating a new world
2.just explore
3.go to beach/desert/ocean/mesa
4.go to biomes o plenty biomes
More steps...

**Expected behavior**
Zawa mobs to spawn in biomes from biomes o plenty mod

**Screenshots**

** Crash Report or Game Log**
If your game crashed, paste your crash report to https://pastebin.com/ or similar service and paste the link in place of this sentence.

**Please complete the following information):**
 - Mod Version Number :zawa-1.12.2-2.0.35

 - Bookworm Version Number :bookworm-1.12.2-2.5.1

 - Forge Version Number :1.12.2-forge-14.23.5.2854

 - Are other mods installed? : BiomesOPlenty-1.12.2-7.0.1.2444-, lilcritters-1.12.2-1.0.0.1, 
                                               NaturalFauna+Mod-1.12.2-1.5.1
 - Is OptiFine installed? : yes

 - Is this bug present in single player or on a server or both? :singleplayer(but I didnt actually tried it 
                                                                                                   on server)

**Comment by 0SoggyMustache0** [comment]
Did you have ZAWA installed before you added BOP?

**Comment by JoelZBub** [comment]
Delete your ZAWA configs and let them regenerate with the BoP biomes.

**Comment by GoodStuffIsBadStuff** [comment]
> Delete your ZAWA configs and let them regenerate with the BoP biomes.
Wow it worked! Thank you so much guys
