### ISSUE TITLE
Way too many poachers

### ISSUE THREAD

**Issue by walterrrrrrrrrr** [0SoggyMustache0/ZAWA#92]
I'm always frustrated when I'm trying to build a zoo in creative or survival but there's just poachers everywhere and I'm not sure how to get rid of them without having to kill every single one with the massive abundance that they spawn in

Id like to see either a way to disable poacher spawning or reduced poacher spawning

I've considered just using other zoo or animal mods but they don't do it like you guys do in this mod.

**Comment by Carooosa** [comment]
ok then use another mod it's not like you're paying for this one anyways.

**Comment by JoelZBub** [comment]
Duplicate of #90 #81 #77 #52 #50 #46 and #29
