### ISSUE TITLE
[Feature Request] I would like to see a potion that baby animals stay babies. 

### ISSUE THREAD

**Issue by Tobiasspet** [0SoggyMustache0/ZAWA#93]
**Feature requests that do not follow this template will be ignored and closed**
**Do NOT suggest animals or model change**

**Is your feature request related to a problem? Please describe.**
Yes babies grow up to fast 

**Describe the solution you'd like**
There would be a brew-able potion or item that can be given to a baby to stop it from aging so that you could enjoy the baby longer! and if you are done with the baby there would be a potion that would let it age again. 

**Describe alternatives you've considered**
havent actually looked into any alternatives thought i would just suggest 

**Additional context**
its fine when its not added! but thought it could be a thing!

**Comment by 0SoggyMustache0** [comment]
Quark has the ability to stop babies from aging [here](https://www.curseforge.com/minecraft/mc-mods/quark). I will leave this open since there should be variable time until animals age or a way to stop them from growing into adults.

**Comment by 0SoggyMustache0** [comment]
This feature has been written and will be available through the data book in 2.1.
