### ISSUE TITLE
To many Watermobs spawn

### ISSUE THREAD

**Issue by blakedj012** [0SoggyMustache0/ZAWA#98]
Extremely many water animals spawn. No matter what I set in the Config it always remains the same. 
Here is a screenshot
https://gyazo.com/98b29418bfaad16f34d1c816268d1d00

Forge 1.12.2 last Zawa Version.  Only this Mod and Bookworm no other Mod installed.

**Comment by JoelZBub** [comment]
That's not *too many*. Do `/forge entity list` in your chat and you'll see that there are not that many mobs there. 
Also... Don't delete our template if you expect any help.

**Comment by blakedj012** [comment]
On my Screen that are not to many ? Are you blind?

**Comment by blakedj012** [comment]
https://gyazo.com/825ac871a06232e8ce7578e61533379b

25 orca on this place...

**Comment by blakedj012** [comment]
fix your config please every change dont work

**Comment by 0SoggyMustache0** [comment]
Stop wasting our time. I am locking this.

**Comment by JoelZBub** [comment]
25 orca. 33 zombies. Too many zombies too? Go spam Mojang
